// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Float.res.
let nan1 = Float.Constants.nan

let isNaN1 = Float.Constants.nan->Float.isNaN
let isNaN2 = Float.isNaN(Float.Constants.nan)

let isFinite1 = 1234.0->Float.isFinite
let isFinite2 = Float.isFinite(1234.0)

let toExponential1 = 77.1234->Float.toExponential
let toExponential2 = Float.toExponential(77.1234)

let toExponentialWithPrecision1 = 77.1234->Float.toExponential(~digits=2)
let toExponentialWithPrecision2 = Float.toExponential(77.1234, ~digits=2)

let toFixed1 = 12345.6789->Float.toFixed
let toFixed2 = Float.toFixed(12345.6789)

let toFixedWithPrecision1 = 12345.6789->Float.toFixed(~digits=1)
let toFixedWithPrecision2 = Float.toFixed(12345.6789, ~digits=1)

let toPrecision1 = 12345.6789->Float.toPrecision
let toPrecision2 = Float.toPrecision(12345.6789)

let toPrecisionWithPrecision1 = 12345.6789->Float.toPrecision(~digits=2)
let toPrecisionWithPrecision2 = Float.toPrecision(12345.6789, ~digits=2)

let toString1 = 12345.6789->Float.toString
let toString2 = Float.toString(12345.6789)

let toStringWithRadix1 = 6.0->Float.toString(~radix=2)
let toStringWithRadix2 = Float.toString(6.0, ~radix=2)

let parse1 = "123"->Float.parseFloat
let parse2 = Float.parseFloat("123")
