// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_BigInt.res.
let fromStringExn1 = "123"->BigInt.fromStringOrThrow
let fromStringExn2 = BigInt.fromStringOrThrow("123")

let land1 = 7n & 4n
let land2 = 7n & 4n
let land3 = 7n->BigInt.toString->BigInt.fromStringOrThrow->BigInt.bitwiseAnd(4n)

let lor1 = 7n->BigInt.bitwiseOr(4n)
let lor2 = BigInt.bitwiseOr(7n, 4n)

let lxor1 = 7n ^ 4n
let lxor2 = 7n ^ 4n

let lnot1 = 2n->Js.BigInt.lnot
let lnot2 = Js.BigInt.lnot(2n)

let lsl1 = 4n << 1n
let lsl2 = 4n << 1n

let asr1 = 8n >> 1n
let asr2 = 8n >> 1n

let toString1 = 123n->BigInt.toString
let toString2 = BigInt.toString(123n)

let toLocaleString1 = 123n->BigInt.toLocaleString
let toLocaleString2 = BigInt.toLocaleString(123n)

// From the stdlib module
let stdlib_fromStringExn1 = "123"->BigInt.fromStringOrThrow
let stdlib_fromStringExn2 = BigInt.fromStringOrThrow("123")

let stdlib_land1 = 7n & 4n
let stdlib_land2 = 7n & 4n

let stdlib_lor1 = BigInt.bitwiseOr(7n, 4n)

let stdlib_lxor1 = 7n ^ 4n
let stdlib_lxor2 = 7n ^ 4n

let stdlib_lnot1 = ~2n
let stdlib_lnot2 = ~2n

let stdlib_lsl1 = 4n << 1n
let stdlib_lsl2 = 4n << 1n

let stdlib_asr1 = 8n >> 1n
let stdlib_asr2 = 8n >> 1n
