// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_WeakSet.res.
// Type alias migration for Js.WeakSet.t
external ws: WeakSet.t<{..}> = "ws"
