// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Js_Types_Interface.res.
/* Implementation to satisfy interface build for tests */

external nullT: Null.t<int> = "nullT"
external nullableT: Nullable.t<string> = "nullableT"
external nullUndefT: Nullable.t<float> = "nullUndefT"

external symbolT: Symbol.t = "symbolT"
external objValT: Type.Classify.object = "objValT"
external functionValT: Type.Classify.function = "functionValT"
