// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Global.res.
let t1: timeoutId = setTimeout(() => (), 1000)
let t2: timeoutId = setTimeoutFloat(() => (), 1000.0)

clearTimeout(t1)

let i1: intervalId = setInterval(() => (), 2000)
let i2: intervalId = setIntervalFloat(() => (), 2000.0)

clearInterval(i1)

let e1 = encodeURI("https://rescript-lang.org?array=[someValue]")
let d1 = decodeURI("https://rescript-lang.org?array=%5BsomeValue%5D")

let e2 = encodeURIComponent("array=[someValue]")
let d2 = decodeURIComponent("array%3D%5BsomeValue%5D")
