// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Extern.res.
// Exercise migrations from Js_extern to new Stdlib APIs

let isNullish = Nullable.isNullable(%raw("null"))
let n = Nullable.null
let u = Nullable.undefined
let ty = Type.typeof("hello")
