// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Obj.res.
let empty1 = Object.make()

let assign1 = Object.make()->Object.assign({"a": 1})
let assign2 = Object.assign(Object.make(), {"a": 1})

let keys1 = {"a": 1, "b": 2}->Object.keysToArray
let keys2 = Object.keysToArray({"a": 1, "b": 2})
