// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_StdlibListLazyPromise.res.
let l1 = List.headOrThrow(list{1})
let l2 = List.tailOrThrow(list{1})
let l3 = List.getOrThrow(list{"a", "b"}, 0)
let l4 = List.shuffle(list{1, 2})

let lazy1 = Lazy.make(() => 1)
let lazy2 = Lazy.make(() => 2)
let v1 = Lazy.get(lazy1)
let v2 = Lazy.get(lazy2)
let b1 = Lazy.isEvaluated(lazy1)

let p = Promise.resolve(5)
let _ = Promise.ignore(p)
