// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Js_More.res.
// Migration tests for new deprecations in packages/@rescript/runtime/Js.res

// typeof migration
let tyNum = typeof(1)

// nullToOption
let nToOpt = Null.toOption(Null.make(1))
