// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Math.res.
// Exercise migrations from Js.Math to Math

let e = Math.Constants.e
let pi = Math.Constants.pi
let ln2 = Math.Constants.ln2
let ln10 = Math.Constants.ln10
let log2e = Math.Constants.log2e
let log10e = Math.Constants.log10e
let sqrt_half = Math.Constants.sqrt1_2
let sqrt2c = Math.Constants.sqrt2

let absInt1 = Math.Int.abs(-5)
let absFloat1 = Math.abs(-3.5)

let acos1 = Math.acos(1.0)
let acosh1 = Math.acosh(1.5)
let asinh1 = Math.asinh(1.0)
let asin1 = Math.asin(0.5)
let atan1 = Math.atan(1.0)
let atanh1 = Math.atanh(0.5)

let atan21 = Math.atan2(~y=0.0, ~x=10.0)

let cbrt1 = Math.cbrt(27.0)

let ceilInt1 = Math.Int.ceil(3.2)
let ceilInt2 = Math.Int.ceil(3.2)
let ceilFloat1 = Math.ceil(3.2)

let clz1 = Math.Int.clz32(255)

let cos1 = Math.cos(0.0)
let cosh1 = Math.cosh(0.0)
let exp1 = Math.exp(1.0)
let expm11 = Math.expm1(1.0)
let log1p1 = Math.log1p(1.0)

let floorInt1 = Math.Int.floor(3.7)
let floorInt2 = Math.Int.floor(3.7)
let floorFloat1 = Math.floor(3.7)

let fround1 = Math.fround(5.05)

let hypot1 = Math.hypot(3.0, 4.0)
let hypotMany1 = Math.hypotMany([3.0, 4.0, 12.0])

let imul1 = Math.Int.imul(3, 4)

let log1 = Math.log(Math.Constants.e)
let log10_1 = Math.log10(1000.0)
let log2_1 = Math.log2(512.0)

let maxInt1 = Math.Int.max(1, 2)
let maxIntMany1 = Math.Int.maxMany([1, 10, 3])
let maxFloat1 = Math.max(1.5, 2.5)
let maxFloatMany1 = Math.maxMany([1.5, 2.5, 0.5])

let minInt1 = Math.Int.min(1, 2)
let minIntMany1 = Math.Int.minMany([1, 10, 3])
let minFloat1 = Math.min(1.5, 2.5)
let minFloatMany1 = Math.minMany([1.5, 2.5, 0.5])

let powInt1 = Math.Int.pow(3, ~exp=4)
let powFloat1 = Math.pow(3.0, ~exp=4.0)

let rand1 = Math.random()

let roundUnsafe1 = Float.toInt(Math.round(3.7))
let round1 = Math.round(3.7)

let signInt1 = Math.Int.sign(-5)
let signFloat1 = Math.sign(-5.0)

let sin1 = Math.sin(0.0)
let sinh1 = Math.sinh(0.0)
let sqrt1 = Math.sqrt(9.0)
let tan1 = Math.tan(0.5)
let tanh1 = Math.tanh(0.0)

let truncUnsafe1 = Float.toInt(Math.trunc(3.7))
let trunc1 = Math.trunc(3.7)
