// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Js_typed_array_Float32_Const.res.
// Float32 constants migration coverage for legacy Js.Typed_array
let bytesF32 = Float32Array.Constants.bytesPerElement
