// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_StdlibPrimitives.res.
let i1 = Int.toExponential(77, ~digits=2)
let i2 = Int.toFixed(300, ~digits=1)
let i3 = Int.toPrecision(100, ~digits=2)
let i4 = Int.toString(6, ~radix=2)
let i5 = Int.range(1, 5, ~options={step: 2})

let f1 = Float.parseInt("10.0", ~radix=2)
let f2 = Float.toExponential(77.0, ~digits=2)
let f3 = Float.toFixed(300.0, ~digits=1)
let f4 = Float.toPrecision(100.0, ~digits=2)
let f5 = Float.toString(6.0, ~radix=2)

let b1 = Bool.fromStringOrThrow("true")

let buf = ArrayBuffer.make(8)
let ab1 = buf->ArrayBuffer.slice(~start=2)

let re1 = RegExp.fromString("\\w+", ~flags="g")
