// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_DataView.res.
let a = DataView.fromBuffer(ArrayBuffer.make(8), ~byteOffset=2)
let b = DataView.fromBuffer(ArrayBuffer.make(8), ~byteOffset=2, ~length=4)
