// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Map.res.
// Type alias migration for Js.Map.t
external m: Map.t<int, string> = "m"
