// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Interface.res.
/* Implementation to satisfy interface build for tests */

external arr: array<int> = "arr"
external reT: RegExp.t = "re"
external json: JSON.t = "json"
external nestedArr: array<RegExp.t> = "nestedArr"

external useSet: Set.t<int> => unit = "useSet"
