// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_WeakMap.res.
// Type alias migration for Js.WeakMap.t
external wm: WeakMap.t<{..}, int> = "wm"
