// This file is autogenerated so it can be type checked.
// It's the migrated version of src/migrate/StdlibMigration_Dict.res.
let d = Dict.make()

let get1 = d->Dict.get("k")
let get2 = Dict.get(d, "k")

let unsafeGet1 = d->Dict.getUnsafe("k")
let unsafeGet2 = Dict.getUnsafe(d, "k")

let set1 = d->Dict.set("k", 1)
let set2 = Dict.set(d, "k", 1)

let keys1 = d->Dict.keysToArray
let keys2 = Dict.keysToArray(d)

let values1 = d->Dict.valuesToArray
let values2 = Dict.valuesToArray(d)

let entries1 = d->Dict.toArray
let entries2 = Dict.toArray(d)

let dStr: dict<string> = Dict.make()
let del1 = dStr->Dict.delete("k")
let del2 = Dict.delete(dStr, "k")

let empty1: dict<int> = Dict.make()

let fromArray1 = [("a", 1), ("b", 2)]->Dict.fromArray
let fromArray2 = Dict.fromArray([("a", 1), ("b", 2)])

let fromList1 = list{("a", 1), ("b", 2)}->Js.Dict.fromList
let fromList2 = Js.Dict.fromList(list{("a", 1), ("b", 2)})

let map2 = Dict.mapValues(d, x => x + 1)
