// Generated by ReScript, PLEASE EDIT WITH CARE


let myRecord = {
  normalField: "Illegal\"Name",
  "Renamed'Field": 42,
  "Illegal-field name": 7,
  UPPERCASE: 100
};

export {
  myRecord,
}
/* No side effect */
