// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dep01 from "@testrepo/dep01/src/Dep01.mjs";

function standalone() {
  Dep01.log();
  console.log("standalone");
}

export {
  standalone,
}
/* Dep01 Not a pure module */
