// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_IntTests from "./Stdlib_IntTests.mjs";
import * as Stdlib_DictTests from "./Stdlib_DictTests.mjs";
import * as Stdlib_JsonTests from "./Stdlib_JsonTests.mjs";
import * as Stdlib_TestTests from "./Stdlib_TestTests.mjs";
import * as Stdlib_ArrayTests from "./Stdlib_ArrayTests.mjs";
import * as Stdlib_ErrorTests from "./Stdlib_ErrorTests.mjs";
import * as Stdlib_FloatTests from "./Stdlib_FloatTests.mjs";
import * as Stdlib_RegExpTest from "./Stdlib_RegExpTest.mjs";
import * as Stdlib_ObjectTests from "./Stdlib_ObjectTests.mjs";
import * as Stdlib_PromiseTest from "./Stdlib_PromiseTest.mjs";
import * as Stdlib_ResultTests from "./Stdlib_ResultTests.mjs";
import * as Stdlib_IteratorTests from "./Stdlib_IteratorTests.mjs";
import * as Stdlib_NullableTests from "./Stdlib_NullableTests.mjs";
import * as Stdlib_TypedArrayTests from "./Stdlib_TypedArrayTests.mjs";

let bign = Stdlib_TestTests.bign;

let TestError = Stdlib_PromiseTest.TestError;

let fail = Stdlib_PromiseTest.fail;

let equal = Stdlib_PromiseTest.equal;

let Creation = Stdlib_PromiseTest.Creation;

let ThenChaining = Stdlib_PromiseTest.ThenChaining;

let Rejection = Stdlib_PromiseTest.Rejection;

let Catching = Stdlib_PromiseTest.Catching;

let Concurrently = Stdlib_PromiseTest.Concurrently;

let panicTest = Stdlib_ErrorTests.panicTest;

let $$catch = Stdlib_IntTests.$$catch;

let nums = Stdlib_ObjectTests.nums;

let d = Stdlib_ObjectTests.d;

let x = Stdlib_ObjectTests.x;

let mkBig = Stdlib_ObjectTests.mkBig;

let assignOverwritesTarget = Stdlib_ObjectTests.assignOverwritesTarget;

let runGetTest = Stdlib_ObjectTests.runGetTest;

let getSymbolTestWhenExists = Stdlib_ObjectTests.getSymbolTestWhenExists;

let forEachIfOkCallFunction = Stdlib_ResultTests.forEachIfOkCallFunction;

let forEachIfErrorDoNotCallFunction = Stdlib_ResultTests.forEachIfErrorDoNotCallFunction;

let num1 = Stdlib_TypedArrayTests.num1;

let num2 = Stdlib_TypedArrayTests.num2;

let num3 = Stdlib_TypedArrayTests.num3;

let assertTrue = Stdlib_TypedArrayTests.assertTrue;

let assertWillThrow = Stdlib_TypedArrayTests.assertWillThrow;

let areSame = Stdlib_TypedArrayTests.areSame;

let o = Stdlib_TypedArrayTests.o;

let decodeJsonTest = Stdlib_JsonTests.decodeJsonTest;

let shouldHandleNullableValues = Stdlib_NullableTests.shouldHandleNullableValues;

let someString = Stdlib_DictTests.someString;

let createdDict = Stdlib_DictTests.createdDict;

let three = Stdlib_DictTests.three;

let intDict = Stdlib_DictTests.intDict;

let PatternMatching = Stdlib_DictTests.PatternMatching;

let Has = Stdlib_DictTests.Has;

let iterator = Stdlib_IteratorTests.iterator;

let syncResult = Stdlib_IteratorTests.syncResult;

let asyncResult = Stdlib_IteratorTests.asyncResult;

let asyncIterator = Stdlib_IteratorTests.asyncIterator;

let eq = Stdlib_RegExpTest.eq;

export {
  bign,
  TestError,
  fail,
  equal,
  Creation,
  ThenChaining,
  Rejection,
  Catching,
  Concurrently,
  panicTest,
  $$catch,
  nums,
  d,
  x,
  mkBig,
  assignOverwritesTarget,
  runGetTest,
  getSymbolTestWhenExists,
  forEachIfOkCallFunction,
  forEachIfErrorDoNotCallFunction,
  num1,
  num2,
  num3,
  assertTrue,
  assertWillThrow,
  areSame,
  o,
  decodeJsonTest,
  shouldHandleNullableValues,
  someString,
  createdDict,
  three,
  intDict,
  PatternMatching,
  Has,
  iterator,
  syncResult,
  asyncResult,
  asyncIterator,
  eq,
}
/* Stdlib_IntTests Not a pure module */
