// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Belt_MapInt = require("@rescript/runtime/lib/js/Belt_MapInt.cjs");

let f = Belt_MapInt.get;

function g() {
  return Belt_MapInt.get(Belt_MapInt.fromArray([
    [
      1,
      "hello"
    ],
    [
      2,
      "world"
    ]
  ]), 1);
}

exports.f = f;
exports.g = g;
/* No side effect */
