// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FileToTest from "../src/FileToTest.mjs";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";

let res = FileToTest.add(1, 2);

if (res !== 3) {
  Pervasives.failwith("Expected " + (3).toString() + ", got " + res.toString());
}

let expected = 3;

export {
  res,
  expected,
}
/* res Not a pure module */
