// Generated by ReScript, PLEASE EDIT WITH CARE


function idInt(x) {
  return x;
}

function idFloat(x) {
  return x;
}

function idBool(x) {
  return x;
}

function idString(x) {
  return x;
}

function idBigInt(x) {
  return x;
}

function idDate(x) {
  return x;
}

function idRegExp(x) {
  return x;
}

function idPromise(x) {
  return x;
}

function idDict(x) {
  return x;
}

function idMap(x) {
  return x;
}

function idWeakMap(x) {
  return x;
}

function idSet(x) {
  return x;
}

function idWeakSet(x) {
  return x;
}

function idArray(x) {
  return x;
}

function idUndefined(x) {
  return x;
}

function idNull(x) {
  return x;
}

function idNullable(x) {
  return x;
}

function idOption(x) {
  return x;
}

function idJSON(x) {
  return x;
}

function idResult(x) {
  return x;
}

function idResultAlias(x) {
  return x;
}

function idRef(x) {
  return x;
}

function returnsUnit() {
  
}

function idTuple(x) {
  return x;
}

function idArrayBuffer(x) {
  return x;
}

function idDataView(x) {
  return x;
}

function idInt8Array(x) {
  return x;
}

function idUint8Array(x) {
  return x;
}

function idUint8ClampedArray(x) {
  return x;
}

function idInt16Array(x) {
  return x;
}

function idUint16Array(x) {
  return x;
}

function idInt32Array(x) {
  return x;
}

function idUint32Array(x) {
  return x;
}

function idFloat32Array(x) {
  return x;
}

function idFloat64Array(x) {
  return x;
}

function idBigInt64Array(x) {
  return x;
}

function idBigUint64Array(x) {
  return x;
}

function idSymbol(x) {
  return x;
}

function idIterator(x) {
  return x;
}

function idAsyncIterator(x) {
  return x;
}

function idOrdering(x) {
  return x;
}

function idIntlCollator(x) {
  return x;
}

function idIntlDateTimeFormat(x) {
  return x;
}

function idIntlListFormat(x) {
  return x;
}

function idIntlLocale(x) {
  return x;
}

function idIntlNumberFormat(x) {
  return x;
}

function idIntlPluralRules(x) {
  return x;
}

function idIntlRelativeTimeFormat(x) {
  return x;
}

function idIntlSegmenter(x) {
  return x;
}

function idIntlSegments(x) {
  return x;
}

function idJsError(x) {
  return x;
}

function idObj(x) {
  return x;
}

export {
  idInt,
  idFloat,
  idBool,
  idString,
  idBigInt,
  idDate,
  idRegExp,
  idPromise,
  idDict,
  idMap,
  idWeakMap,
  idSet,
  idWeakSet,
  idArray,
  idUndefined,
  idNull,
  idNullable,
  idOption,
  idJSON,
  idResult,
  idResultAlias,
  idRef,
  returnsUnit,
  idTuple,
  idArrayBuffer,
  idDataView,
  idInt8Array,
  idUint8Array,
  idUint8ClampedArray,
  idInt16Array,
  idUint16Array,
  idInt32Array,
  idUint32Array,
  idFloat32Array,
  idFloat64Array,
  idBigInt64Array,
  idBigUint64Array,
  idSymbol,
  idIterator,
  idAsyncIterator,
  idOrdering,
  idIntlCollator,
  idIntlDateTimeFormat,
  idIntlListFormat,
  idIntlLocale,
  idIntlNumberFormat,
  idIntlPluralRules,
  idIntlRelativeTimeFormat,
  idIntlSegmenter,
  idIntlSegments,
  idJsError,
  idObj,
}
/* No side effect */
