// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(b, x, _n) {
  while (true) {
    let n = _n;
    if (n > 100000) {
      return false;
    }
    if (!b) {
      return false;
    }
    _n = n + 1 | 0;
    continue;
  };
}

function or_f(b, x, _n) {
  while (true) {
    let n = _n;
    if (n > 100000) {
      return false;
    }
    if (b) {
      return true;
    }
    _n = n + 1 | 0;
    continue;
  };
}

Mocha.describe("And_or_tailcall_test", () => {
  Mocha.test("and_tail", () => Test_utils.eq("File \"and_or_tailcall_test.res\", line 21, characters 7-14", false, f(true, 1, 0)));
  Mocha.test("or_tail", () => Test_utils.eq("File \"and_or_tailcall_test.res\", line 24, characters 7-14", false, or_f(false, 1, 0)));
});

export {
  f,
  or_f,
}
/*  Not a pure module */
