// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f0(x, y, z) {
  return (x + y | 0) + z | 0;
}

function f1(x) {
  return (y, z) => (x + y | 0) + z | 0;
}

function f2(x, y) {
  return z => (x + y | 0) + z | 0;
}

function f3(x) {
  return (y, z) => (x + y | 0) + z | 0;
}

Mocha.describe("Arity_deopt", () => {
  Mocha.test("arity_deopt_tests", () => {
    Test_utils.eq("File \"arity_deopt.res\", line 43, characters 7-14", 6, 6);
    Test_utils.eq("File \"arity_deopt.res\", line 44, characters 7-14", 6, 6);
    Test_utils.eq("File \"arity_deopt.res\", line 45, characters 7-14", 6, 6);
    Test_utils.eq("File \"arity_deopt.res\", line 46, characters 7-14", 6, 6);
  });
});

export {
  f0,
  f1,
  f2,
  f3,
}
/*  Not a pure module */
