// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_util from "@rescript/runtime/lib/es6/Primitive_util.js";

function tToJs(param) {
  return {
    x: param.x,
    y: param.y,
    z: param.z
  };
}

function tFromJs(param) {
  return {
    x: param.x,
    y: param.y,
    z: param.z
  };
}

let v0 = {
  x: 3,
  y: false,
  z: false
};

let v1 = {
  x: 3,
  y: false,
  z: ""
};

let _map = {"a":"a","b":"b","c":"c"};

function xToJs(param) {
  return param;
}

function xFromJs(param) {
  return Primitive_util.raiseWhenNotFound(_map[param]);
}

function idx(v) {
  Test_utils.eq("File \"ast_abstract_test.res\", line 21, characters 18-25", xFromJs(v), v);
}

let x0 = "a";

let x1 = "b";

Mocha.describe("Ast_abstract_test", () => {
  Mocha.test("jsConverter roundtrip for #a", () => idx("a"));
  Mocha.test("jsConverter roundtrip for #b", () => idx("b"));
  Mocha.test("jsConverter roundtrip for #c", () => idx("c"));
});

export {
  tToJs,
  tFromJs,
  v0,
  v1,
  xToJs,
  xFromJs,
  idx,
  x0,
  x1,
}
/*  Not a pure module */
