// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_List from "@rescript/runtime/lib/es6/Belt_List.js";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let Block = {};

let v0 = {
  TAG: "A",
  _0: 0,
  _1: 1
};

let Block$1 = {};

let v1 = {
  TAG: "A",
  _0: 0,
  _1: 1
};

let N = {
  Block: Block$1,
  v1: v1
};

let Caml_obj = {};

let List = {};

let V = {
  List: List
};

let f = Primitive_object.equal;

Mocha.describe("Block_alias_test", () => {
  Mocha.test("block_alias_tests", () => {
    Test_utils.eq("File \"block_alias_test.res\", line 28, characters 7-14", Belt_List.length({
      hd: 1,
      tl: {
        hd: 2,
        tl: /* [] */0
      }
    }), 2);
    Test_utils.ok("File \"block_alias_test.res\", line 29, characters 7-14", Primitive_object.equal(v0, {
      TAG: "A",
      _0: 0,
      _1: 1
    }));
    Test_utils.eq("File \"block_alias_test.res\", line 30, characters 7-14", v0, v1);
  });
});

let h = Belt_List.length;

export {
  Block,
  v0,
  N,
  Caml_obj,
  V,
  f,
  h,
}
/*  Not a pure module */
