// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_bool_equal from "./test_bool_equal.mjs";

Mocha.describe("boolean", () => {
  Mocha.test("bool_equal", () => Test_bool_equal.assertions());
});

/*  Not a pure module */
