// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_MapInt from "@rescript/runtime/lib/es6/Belt_MapInt.js";
import * as Belt_SetInt from "@rescript/runtime/lib/es6/Belt_SetInt.js";

let mapOfArray = Belt_MapInt.fromArray;

let setOfArray = Belt_SetInt.fromArray;

function emptyMap() {
  
}

Mocha.describe("Bs_map_test", () => {
  Mocha.test("bs map test", () => {
    let v = Belt_Array.makeByAndShuffle(1000000, i => [
      i,
      i
    ]);
    let u = Belt_MapInt.fromArray(v);
    Belt_MapInt.checkInvariantInternal(u);
    let firstHalf = Belt_Array.slice(v, 0, 2000);
    let xx = Belt_Array.reduce(firstHalf, u, (acc, param) => Belt_MapInt.remove(acc, param[0]));
    Belt_MapInt.checkInvariantInternal(u);
    Belt_MapInt.checkInvariantInternal(xx);
  });
});

let M;

let N;

let A;

export {
  M,
  N,
  A,
  mapOfArray,
  setOfArray,
  emptyMap,
}
/*  Not a pure module */
