// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_Id from "@rescript/runtime/lib/es6/Belt_Id.js";
import * as Belt_Set from "@rescript/runtime/lib/es6/Belt_Set.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Array_data_util from "./array_data_util.mjs";
import * as Belt_MutableMap from "@rescript/runtime/lib/es6/Belt_MutableMap.js";

let Icmp = Belt_Id.comparable(Primitive_int.compare);

function f(x) {
  return Belt_MutableMap.fromArray(x, Icmp);
}

function ff(x) {
  return Belt_Set.fromArray(x, Icmp);
}

function randomRange(i, j) {
  return Belt_Array.map(Array_data_util.randomRange(i, j), x => [
    x,
    x
  ]);
}

Mocha.describe("Bs_poly_mutable_map_test", () => {
  Mocha.test("mutable map operations with small range", () => {
    let a0 = Belt_MutableMap.fromArray(randomRange(0, 10), Icmp);
    Belt_MutableMap.set(a0, 3, 33);
    Test_utils.eq("File \"bs_poly_mutable_map_test.res\", line 26, characters 7-14", Belt_MutableMap.getExn(a0, 3), 33);
    Belt_MutableMap.removeMany(a0, [
      7,
      8,
      0,
      1,
      3,
      2,
      4,
      922,
      4,
      5,
      6
    ]);
    Test_utils.eq("File \"bs_poly_mutable_map_test.res\", line 28, characters 7-14", Belt_MutableMap.keysToArray(a0), [
      9,
      10
    ]);
    Belt_MutableMap.removeMany(a0, Array_data_util.randomRange(0, 100));
    Test_utils.eq("File \"bs_poly_mutable_map_test.res\", line 30, characters 7-14", Belt_MutableMap.isEmpty(a0), true);
  });
  Mocha.test("mutable map operations with large range", () => {
    let a0 = Belt_MutableMap.fromArray(randomRange(0, 10000), Icmp);
    Belt_MutableMap.set(a0, 2000, 33);
    Belt_MutableMap.removeMany(a0, Belt_Array.map(randomRange(0, 1998), prim => prim[0]));
    Belt_MutableMap.removeMany(a0, Belt_Array.map(randomRange(2002, 11000), prim => prim[0]));
    Test_utils.eq("File \"bs_poly_mutable_map_test.res\", line 38, characters 7-14", Belt_MutableMap.toArray(a0), [
      [
        1999,
        1999
      ],
      [
        2000,
        33
      ],
      [
        2001,
        2001
      ]
    ]);
  });
});

let M;

let N;

let A;

let I;

export {
  Icmp,
  M,
  N,
  A,
  I,
  f,
  ff,
  randomRange,
}
/* Icmp Not a pure module */
