// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_float from "@rescript/runtime/lib/es6/Primitive_float.js";

let five = BigInt("5");

Mocha.describe("Caml_compare_bigint_test", () => {
  Mocha.test("compare: 123 and 555555", () => {
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 10, characters 7-14", BigInt("555555") > BigInt("123"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 11, characters 7-14", BigInt("123") < BigInt("555555"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 12, characters 7-14", BigInt("123") < BigInt("555555"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 13, characters 7-14", BigInt("123") <= BigInt("555555"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 14, characters 7-14", BigInt("555555") > BigInt("123"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 15, characters 7-14", BigInt("555555") >= BigInt("123"));
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 16, characters 7-14", Primitive_float.min(BigInt("555555"), BigInt("123")), BigInt("123"));
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 17, characters 7-14", Primitive_float.min(BigInt("123"), BigInt("555555")), BigInt("123"));
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 18, characters 7-14", Primitive_float.max(BigInt("555555"), BigInt("123")), BigInt("555555"));
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 19, characters 7-14", Primitive_float.max(BigInt("123"), BigInt("555555")), BigInt("555555"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 20, characters 7-14", BigInt("555555") !== BigInt("123"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 21, characters 7-14", BigInt("123") !== BigInt("555555"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 22, characters 7-14", BigInt("555555") !== BigInt("123"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 23, characters 7-14", BigInt("123") !== BigInt("555555"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 24, characters 7-14", BigInt("555555") !== BigInt("123"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 25, characters 7-14", BigInt("123") !== BigInt("555555"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 26, characters 7-14", BigInt("555555") !== BigInt("123"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 27, characters 7-14", BigInt("123") !== BigInt("555555"));
  });
  Mocha.test("compare: 98765 and 98765", () => {
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 31, characters 7-14", BigInt("98765") >= BigInt("98765"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 32, characters 7-14", BigInt("98765") <= BigInt("98765"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 33, characters 7-14", BigInt("98765") <= BigInt("98765"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 34, characters 7-14", BigInt("98765") >= BigInt("98765"));
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 35, characters 7-14", Primitive_float.min(BigInt("98765"), BigInt("98765")), BigInt("98765"));
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 36, characters 7-14", Primitive_float.max(BigInt("98765"), BigInt("98765")), BigInt("98765"));
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 37, characters 7-14", Primitive_float.compare(BigInt("98765"), BigInt("98765")), 0);
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 38, characters 7-14", Primitive_float.compare(BigInt("98765"), BigInt("98765")), 0);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 39, characters 7-14", BigInt("98765") === BigInt("98765"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 40, characters 7-14", BigInt("98765") === BigInt("98765"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 41, characters 7-14", BigInt("98765") === BigInt("98765"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 42, characters 7-14", BigInt("98765") === BigInt("98765"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 43, characters 7-14", BigInt("98765") === BigInt("98765"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 44, characters 7-14", BigInt("98765") === BigInt("98765"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 45, characters 7-14", BigInt("98765") === BigInt("98765"));
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 46, characters 7-14", BigInt("98765") === BigInt("98765"));
  });
  Mocha.test("same instance", () => {
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 50, characters 7-14", five >= five);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 51, characters 7-14", five <= five);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 52, characters 7-14", five <= five);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 53, characters 7-14", five >= five);
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 54, characters 7-14", Primitive_float.min(five, five), five);
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 55, characters 7-14", Primitive_float.max(five, five), five);
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 56, characters 7-14", Primitive_float.compare(five, five), 0);
    Test_utils.eq("File \"caml_compare_bigint_test.res\", line 57, characters 7-14", Primitive_float.compare(five, five), 0);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 58, characters 7-14", five === five);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 59, characters 7-14", five === five);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 60, characters 7-14", five === five);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 61, characters 7-14", five === five);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 62, characters 7-14", five === five);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 63, characters 7-14", five === five);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 64, characters 7-14", five === five);
    Test_utils.ok("File \"caml_compare_bigint_test.res\", line 65, characters 7-14", five === five);
  });
});

export {
  five,
}
/* five Not a pure module */
