// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(h) {
  return h.x.y.z;
}

function f2(h) {
  return h.x.y.z;
}

function f3(h, x, y) {
  return h.paint(x, y).draw(x, y);
}

function f4(h, x, y) {
  h.paint = [
    x,
    y
  ];
  h.paint.draw = [
    x,
    y
  ];
}

Mocha.describe("Chain_code_test", () => {
  Mocha.test("chain code test", () => Test_utils.eq("File \"chain_code_test.res\", line 21, characters 7-14", 32, ({
    x: {
      y: {
        z: 32
      }
    }
  }).x.y.z));
});

export {
  f,
  f2,
  f3,
  f4,
}
/*  Not a pure module */
