// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let v = {
  contents: 1
};

v.contents = v.contents + 1 | 0;

let a = v.contents;

Mocha.describe("Condition_compilation_test", () => {
  Mocha.test("condition compilation vv", () => Test_utils.eq("File \"condition_compilation_test.res\", line 52, characters 44-51", 3, 3));
  Mocha.test("condition compilation v", () => Test_utils.eq("File \"condition_compilation_test.res\", line 53, characters 43-50", v.contents, 2));
});

let b = "u";

let buffer_size = 1;

let vv = 3;

let version_gt_3 = true;

let version = -1;

let ocaml_veriosn = "unknown";

export {
  b,
  buffer_size,
  vv,
  v,
  a,
  version_gt_3,
  version,
  ocaml_veriosn,
}
/*  Not a pure module */
