// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let a = [
  0,
  1,
  2
];

let b = [
  0,
  1,
  2
];

let c = [
  0,
  1,
  2,
  3,
  4,
  5
];

function f() {
  a[0] = 3.0;
  b[0] = 3;
}

function h() {
  return c;
}

function g() {
  f();
  Test_utils.eq("File \"const_block_test.res\", line 25, characters 5-12", [
    a[0],
    b[0]
  ], [
    3.0,
    3
  ]);
}

Mocha.describe("Const_block_test", () => {
  Mocha.test("const_block_test", () => g());
  Mocha.test("avoid_mutable_inline_test", () => {
    c[0] = 3;
    c[1] = 4;
    Test_utils.eq("File \"const_block_test.res\", line 40, characters 7-14", [
      3,
      4,
      2,
      3,
      4,
      5
    ], c);
  });
});

let v = [
  0,
  1,
  2,
  3,
  4,
  5
];

export {
  a,
  b,
  c,
  v,
  f,
  h,
}
/*  Not a pure module */
