// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_array from "@rescript/runtime/lib/es6/Primitive_array.js";

let a = [
  0,
  1,
  2
];

let b = [
  0,
  1,
  2
];

let c = [
  0,
  1,
  2,
  3,
  4,
  5
];

function f() {
  Primitive_array.set(a, 0, 3.0);
  Primitive_array.set(b, 0, 3);
}

function h() {
  return c;
}

function g() {
  f();
  Test_utils.eq("File \"const_block_test.res\", line 26, characters 5-12", [
    Primitive_array.get(a, 0),
    Primitive_array.get(b, 0)
  ], [
    3.0,
    3
  ]);
}

Mocha.describe("Const_block_test", () => {
  Mocha.test("const_block_test", () => g());
  Mocha.test("avoid_mutable_inline_test", () => {
    Primitive_array.set(c, 0, 3);
    Primitive_array.set(c, 1, 4);
    Test_utils.eq("File \"const_block_test.res\", line 41, characters 7-14", [
      3,
      4,
      2,
      3,
      4,
      5
    ], c);
  });
});

let v = [
  0,
  1,
  2,
  3,
  4,
  5
];

export {
  a,
  b,
  c,
  v,
  f,
  h,
}
/*  Not a pure module */
