// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Test_utils from "./test_utils.mjs";

function test_sum() {
  let v = {
    contents: 0
  };
  let f = (_n, _acc) => {
    while (true) {
      let acc = _acc;
      let n = _n;
      if (n === 0) {
        return acc();
      }
      _acc = () => {
        v.contents = v.contents + n | 0;
        return acc();
      };
      _n = n - 1 | 0;
      continue;
    };
  };
  f(10, () => {});
  return v.contents;
}

function test_closure() {
  let v = {
    contents: 0
  };
  let arr = Belt_Array.make(6, x => x);
  for (let i = 0; i <= 5; ++i) {
    arr[i] = param => i;
  }
  Belt_Array.forEach(arr, i => {
    v.contents = v.contents + i(0) | 0;
  });
  return v.contents;
}

function test_closure2() {
  let v = {
    contents: 0
  };
  let arr = Belt_Array.make(6, x => x);
  for (let i = 0; i <= 5; ++i) {
    let j = i + i | 0;
    arr[i] = param => j;
  }
  Belt_Array.forEach(arr, i => {
    v.contents = v.contents + i(0) | 0;
  });
  return v.contents;
}

Mocha.describe("Cps_test", () => {
  Mocha.test("cps_test_sum", () => Test_utils.eq("File \"cps_test.res\", line 43, characters 32-39", 55, test_sum()));
  Mocha.test("cps_test_closure", () => Test_utils.eq("File \"cps_test.res\", line 44, characters 36-43", 15, test_closure()));
  Mocha.test("cps_test_closure2", () => Test_utils.eq("File \"cps_test.res\", line 45, characters 37-44", 30, test_closure2()));
});

export {
  test_sum,
  test_closure,
  test_closure2,
}
/*  Not a pure module */
