// Generated by ReScript, PLEASE EDIT WITH CARE


function decode(data) {
  let match = JSON.parse(data);
  if (typeof match !== "object" || match === null || Array.isArray(match)) {
    return [];
  }
  let match$1 = match.type;
  let exit = 0;
  if (typeof match$1 === "string") {
    if (match$1 === "a") {
      return ["A"];
    }
    exit = 1;
  } else {
    exit = 1;
  }
  if (exit === 1) {
    let match$2 = match.type;
    let exit$1 = 0;
    if (typeof match$2 === "string") {
      if (match$2 === "b") {
        return ["B"];
      }
      exit$1 = 2;
    } else {
      exit$1 = 2;
    }
    if (exit$1 === 2) {
      let match$3 = match.type;
      let exit$2 = 0;
      if (typeof match$3 === "string") {
        if (match$3 === "c") {
          return ["C"];
        }
        exit$2 = 3;
      } else {
        exit$2 = 3;
      }
      if (exit$2 === 3) {
        let match$4 = match.type;
        let exit$3 = 0;
        if (typeof match$4 === "string") {
          if (match$4 === "d") {
            return ["D"];
          }
          exit$3 = 4;
        } else {
          exit$3 = 4;
        }
        if (exit$3 === 4) {
          let match$5 = match.type;
          let exit$4 = 0;
          if (typeof match$5 === "string") {
            if (match$5 === "e") {
              return ["E"];
            }
            exit$4 = 5;
          } else {
            exit$4 = 5;
          }
          if (exit$4 === 5) {
            let match$6 = match.type;
            if (typeof match$6 === "string") {
              if (match$6 === "f") {
                return ["F"];
              } else {
                return [];
              }
            } else {
              return [];
            }
          }
        }
      }
    }
  }
}

export {
  decode,
}
/* No side effect */
