// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

Mocha.describe("Div_by_zero_test", () => {
  Mocha.test("division by zero exception handling", () => {
    Test_utils.throws("File \"div_by_zero_test.res\", line 6, characters 11-18", () => {
      Primitive_int.div(3, 0);
    });
    Test_utils.throws("File \"div_by_zero_test.res\", line 7, characters 11-18", () => {
      Primitive_int.mod_(3, 0);
    });
  });
  Mocha.test("division function with error", () => {});
});

/*  Not a pure module */
