// Generated by ReScript, PLEASE EDIT WITH CARE


function fn1(v) {
  return v.field;
}

let dict = {
  key: 1,
  KEY: 1
};

let x = {
  "🎉": 42
};

export {
  fn1,
  dict,
  x,
}
/* No side effect */
