// Generated by ReScript, PLEASE EDIT WITH CARE


let X = {};

let process = globalThis.process;

let proc = process;

let New = {};

function url(prim) {
  return new URL(prim);
}

let Global = {};

let $$parseInt = parseInt;

export {
  X,
  process,
  proc,
  New,
  url,
  Global,
  $$parseInt,
}
/* process Not a pure module */
