// Generated by ReScript, PLEASE EDIT WITH CARE


let URL = {};

globalThis.URL.revokeObjectURL("some url");

globalThis.URL.revokeObjectURL("some url");

let MyURL;

export {
  URL,
  MyURL,
}
/*  Not a pure module */
