// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function Make (){
  this.data = []
  for(var i = 0; i < arguments.length; ++i){
   this.data[i] = arguments[i]
}
}

Make.prototype.sum = function(){
  var result  = 0;
  for(var k = 0; k < this.data.length; ++k){
    result = result + this.data[k]
  };
  return result
}

Make.prototype.add = function(){

}
;

function f(x) {
  return x.test("a", "b").test("a", "b");
}

let v = new Make(1, 2, 3, 4);

let u = v.sum();

Mocha.describe("Ffi_splice_test", () => {
  Mocha.test("ffi splice test", () => Test_utils.eq("File \"ffi_splice_test.res\", line 48, characters 7-14", u, 10));
});

export {
  f,
  v,
  u,
}
/*  Not a pure module */
