// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Ffi_array_test", () => {
  Mocha.test("ffi array test", () => Test_utils.eq("File \"ffi_array_test.res\", line 8, characters 7-14", [
    1,
    2,
    3,
    4
  ].map(x => x + 1 | 0), [
    2,
    3,
    4,
    5
  ]));
});

/*  Not a pure module */
