// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_float from "@rescript/runtime/lib/es6/Primitive_float.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let float_compare = Primitive_float.compare;

let generic_compare = Primitive_object.compare;

function float_equal(x, y) {
  return x === y;
}

let generic_equal = Primitive_object.equal;

function float_notequal(x, y) {
  return x !== y;
}

let generic_notequal = Primitive_object.notequal;

function float_lessthan(x, y) {
  return x < y;
}

let generic_lessthan = Primitive_object.lessthan;

function float_greaterthan(x, y) {
  return x > y;
}

let generic_greaterthan = Primitive_object.greaterthan;

function float_lessequal(x, y) {
  return x <= y;
}

let generic_lessequal = Primitive_object.lessequal;

function float_greaterequal(x, y) {
  return x >= y;
}

let generic_greaterequal = Primitive_object.greaterequal;

Mocha.describe("Float_test", () => {
  Mocha.test("float_test_1", () => {
    Test_utils.eq("File \"float_test.res\", line 21, characters 7-14", Pervasives.classify_float(3), "FP_normal");
    Test_utils.eq("File \"float_test.res\", line 23, characters 6-13", [
      -1,
      1,
      1
    ], [
      [
        1,
        3
      ],
      [
        2,
        1
      ],
      [
        3,
        2
      ]
    ].map(param => Primitive_float.compare(param[0], param[1])).map(x => {
      if (x > 0) {
        return 1;
      } else if (x < 0) {
        return -1;
      } else {
        return 0;
      }
    }));
    Test_utils.eq("File \"float_test.res\", line 38, characters 7-14", Math.log10(10), 1);
    Test_utils.eq("File \"float_test.res\", line 39, characters 7-14", Number("3.0"), 3.0);
    Test_utils.eq("File \"float_test.res\", line 40, characters 7-14", Primitive_float.compare(NaN, NaN), 0);
    Test_utils.eq("File \"float_test.res\", line 41, characters 7-14", Primitive_object.compare(NaN, NaN), 0);
    Test_utils.eq("File \"float_test.res\", line 42, characters 7-14", Primitive_float.compare(NaN, Pervasives.neg_infinity), -1);
    Test_utils.eq("File \"float_test.res\", line 43, characters 7-14", Primitive_object.compare(NaN, Pervasives.neg_infinity), -1);
    Test_utils.eq("File \"float_test.res\", line 44, characters 7-14", Primitive_float.compare(Pervasives.neg_infinity, NaN), 1);
    Test_utils.eq("File \"float_test.res\", line 45, characters 7-14", Primitive_object.compare(Pervasives.neg_infinity, NaN), 1);
    Test_utils.eq("File \"float_test.res\", line 46, characters 7-14", NaN === NaN, false);
    Test_utils.eq("File \"float_test.res\", line 47, characters 7-14", Primitive_object.equal(NaN, NaN), false);
    Test_utils.eq("File \"float_test.res\", line 48, characters 7-14", 4.2 === NaN, false);
    Test_utils.eq("File \"float_test.res\", line 49, characters 7-14", Primitive_object.equal(4.2, NaN), false);
    Test_utils.eq("File \"float_test.res\", line 50, characters 7-14", NaN === 4.2, false);
    Test_utils.eq("File \"float_test.res\", line 51, characters 7-14", Primitive_object.equal(NaN, 4.2), false);
    Test_utils.eq("File \"float_test.res\", line 52, characters 7-14", NaN !== NaN, true);
    Test_utils.eq("File \"float_test.res\", line 53, characters 7-14", Primitive_object.notequal(NaN, NaN), true);
    Test_utils.eq("File \"float_test.res\", line 54, characters 7-14", 4.2 !== NaN, true);
    Test_utils.eq("File \"float_test.res\", line 55, characters 7-14", Primitive_object.notequal(4.2, NaN), true);
    Test_utils.eq("File \"float_test.res\", line 56, characters 7-14", NaN !== 4.2, true);
    Test_utils.eq("File \"float_test.res\", line 57, characters 7-14", Primitive_object.notequal(NaN, 4.2), true);
    Test_utils.eq("File \"float_test.res\", line 58, characters 7-14", NaN < NaN, false);
    Test_utils.eq("File \"float_test.res\", line 59, characters 7-14", Primitive_object.lessthan(NaN, NaN), false);
    Test_utils.eq("File \"float_test.res\", line 60, characters 7-14", 4.2 < NaN, false);
    Test_utils.eq("File \"float_test.res\", line 61, characters 7-14", Primitive_object.lessthan(4.2, NaN), false);
    Test_utils.eq("File \"float_test.res\", line 62, characters 7-14", NaN < 4.2, false);
    Test_utils.eq("File \"float_test.res\", line 63, characters 7-14", Primitive_object.lessthan(NaN, 4.2), false);
    Test_utils.eq("File \"float_test.res\", line 64, characters 7-14", NaN > NaN, false);
    Test_utils.eq("File \"float_test.res\", line 65, characters 7-14", Primitive_object.greaterthan(NaN, NaN), false);
    Test_utils.eq("File \"float_test.res\", line 66, characters 7-14", 4.2 > NaN, false);
    Test_utils.eq("File \"float_test.res\", line 67, characters 7-14", Primitive_object.greaterthan(4.2, NaN), false);
    Test_utils.eq("File \"float_test.res\", line 68, characters 7-14", NaN > 4.2, false);
    Test_utils.eq("File \"float_test.res\", line 69, characters 7-14", Primitive_object.greaterthan(NaN, 4.2), false);
    Test_utils.eq("File \"float_test.res\", line 70, characters 7-14", NaN <= NaN, false);
    Test_utils.eq("File \"float_test.res\", line 71, characters 7-14", Primitive_object.lessequal(NaN, NaN), false);
    Test_utils.eq("File \"float_test.res\", line 72, characters 7-14", Primitive_object.lessequal(4.2, NaN), false);
    Test_utils.eq("File \"float_test.res\", line 73, characters 7-14", Primitive_object.lessequal(4.2, NaN), false);
    Test_utils.eq("File \"float_test.res\", line 74, characters 7-14", Primitive_object.lessequal(NaN, 4.2), false);
    Test_utils.eq("File \"float_test.res\", line 75, characters 7-14", Primitive_object.lessequal(NaN, 4.2), false);
    Test_utils.eq("File \"float_test.res\", line 76, characters 7-14", NaN >= NaN, false);
    Test_utils.eq("File \"float_test.res\", line 77, characters 7-14", Primitive_object.greaterequal(NaN, NaN), false);
    Test_utils.eq("File \"float_test.res\", line 78, characters 7-14", 4.2 >= NaN, false);
    Test_utils.eq("File \"float_test.res\", line 79, characters 7-14", Primitive_object.greaterequal(4.2, NaN), false);
    Test_utils.eq("File \"float_test.res\", line 80, characters 7-14", NaN >= 4.2, false);
    Test_utils.eq("File \"float_test.res\", line 81, characters 7-14", Primitive_object.greaterequal(NaN, 4.2), false);
  });
});

export {
  float_compare,
  generic_compare,
  float_equal,
  generic_equal,
  float_notequal,
  generic_notequal,
  float_lessthan,
  generic_lessthan,
  float_greaterthan,
  generic_greaterthan,
  float_lessequal,
  generic_lessequal,
  float_greaterequal,
  generic_greaterequal,
}
/*  Not a pure module */
