// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function tst() {
  for (let i = (console.log("hi"), 0), i_finish = (console.log("hello"), 3); i <= i_finish; ++i) {
    
  }
}

function test2() {
  let v = 0;
  v = 3;
  v = 10;
  for (let i = 0; i <= 1; ++i) {
    
  }
  return v;
}

Mocha.describe("For_side_effect_test", () => {
  Mocha.test("for_order", () => Test_utils.eq("File \"for_side_effect_test.res\", line 31, characters 7-14", 10, test2()));
});

export {
  tst,
  test2,
}
/*  Not a pure module */
