// Generated by ReScript, PLEASE EDIT WITH CARE


async function f(p1, p2, p3) {
  'use cache';
  return await new Promise((resolve, _reject) => resolve([
    p1,
    p2,
    p3
  ]));
}

let result = f(1, 2, 3);

export {
  f,
  result,
}
/* result Not a pure module */
