// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Functor_def from "./functor_def.mjs";
import * as Functor_inst from "./functor_inst.mjs";

let Y0 = Functor_def.Make(Functor_inst);

let Y1 = Functor_def.Make(Functor_inst);

Mocha.describe("Functor_app_test", () => {
  Mocha.test("functor_app_test", () => {
    Test_utils.eq("File \"functor_app_test.res\", line 12, characters 7-14", Y0.h(1, 2), 4);
    Test_utils.eq("File \"functor_app_test.res\", line 13, characters 7-14", Y1.h(2, 3), 6);
    let v = Functor_def.$$return();
    Test_utils.eq("File \"functor_app_test.res\", line 17, characters 7-14", v, 2);
  });
});

export {
  Y0,
  Y1,
}
/* Y0 Not a pure module */
