// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_List from "@rescript/runtime/lib/es6/Belt_List.js";
import * as Test_utils from "./test_utils.mjs";

let v = {
  contents: 0
};

function Make(U) {
  v.contents = v.contents + 1 | 0;
  v.contents = v.contents + 1 | 0;
  v.contents = v.contents + 1 | 0;
  return U;
}

function f() {
  v.contents = v.contents + 1 | 0;
  v.contents = v.contents + 1 | 0;
  v.contents = v.contents + 1 | 0;
  v.contents = v.contents + 1 | 0;
  v.contents = v.contents + 1 | 0;
  v.contents = v.contents + 1 | 0;
  return Belt_List;
}

function g() {
  return Belt_List.length({
    hd: 1,
    tl: {
      hd: 2,
      tl: {
        hd: 3,
        tl: {
          hd: 4,
          tl: /* [] */0
        }
      }
    }
  });
}

function xx() {
  v.contents = v.contents + 1 | 0;
  v.contents = v.contents + 1 | 0;
  v.contents = v.contents + 1 | 0;
  return Belt_List;
}

Mocha.describe("Global_module_alias_test", () => {
  Mocha.test("module alias basic operations", () => Test_utils.eq("File \"global_module_alias_test.res\", line 72, characters 7-14", Belt_List.length({
    hd: 1,
    tl: {
      hd: 2,
      tl: /* [] */0
    }
  }), 2));
  Mocha.test("module alias with Make functor", () => {
    v.contents = v.contents + 1 | 0;
    v.contents = v.contents + 1 | 0;
    v.contents = v.contents + 1 | 0;
    v.contents = v.contents + 1 | 0;
    v.contents = v.contents + 1 | 0;
    v.contents = v.contents + 1 | 0;
    v.contents = v.contents + 1 | 0;
    v.contents = v.contents + 1 | 0;
    v.contents = v.contents + 1 | 0;
    v.contents = v.contents + 1 | 0;
    v.contents = v.contents + 1 | 0;
    v.contents = v.contents + 1 | 0;
    Test_utils.eq("File \"global_module_alias_test.res\", line 77, characters 7-14", v.contents, 12);
  });
  Mocha.test("module alias unpacking", () => Test_utils.eq("File \"global_module_alias_test.res\", line 81, characters 7-14", g(), 4));
  Mocha.test("module alias with functor applications", () => {
    let V = xx();
    Test_utils.eq("File \"global_module_alias_test.res\", line 86, characters 7-14", V.length({
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 3,
          tl: /* [] */0
        }
      }
    }), 3);
    Test_utils.eq("File \"global_module_alias_test.res\", line 87, characters 7-14", v.contents, 15);
    let H = f();
    Test_utils.eq("File \"global_module_alias_test.res\", line 89, characters 7-14", H.length({
      hd: 1,
      tl: {
        hd: 2,
        tl: /* [] */0
      }
    }), 2);
    Test_utils.eq("File \"global_module_alias_test.res\", line 90, characters 7-14", v.contents, 21);
  });
});

let A;

let B;

let C;

let D;

let E;

let F;

export {
  A,
  B,
  C,
  D,
  E,
  F,
  v,
  Make,
  f,
  g,
  xx,
}
/*  Not a pure module */
