// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let v = {
  RE_EXN_ID: "Not_found"
};

let u = {
  RE_EXN_ID: "Not_found"
};

let s = {
  RE_EXN_ID: "End_of_file"
};

Mocha.describe("Global_exception_regression_test", () => {
  Mocha.test("not_found_equal", () => Test_utils.eq("File \"global_exception_regression_test.res\", line 11, characters 7-14", u, v));
  Mocha.test("not_found_not_equal_end_of_file", () => Test_utils.eq("File \"global_exception_regression_test.res\", line 14, characters 7-14", Primitive_object.notequal(u, s), true));
});

export {
  v,
  u,
  s,
}
/*  Not a pure module */
