// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Test_google_closure from "./test_google_closure.mjs";

Mocha.describe("Closure", () => {
  Mocha.test("partial", () => Test_utils.eq("File \"google_closure_test.res\", line 7, characters 6-13", [
    Test_google_closure.a,
    Test_google_closure.b,
    Test_google_closure.c
  ], [
    "3",
    101,
    [
      1,
      2
    ]
  ]));
});

/*  Not a pure module */
