// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_bool from "@rescript/runtime/lib/es6/Primitive_bool.js";

let expected = [
  false,
  false,
  true,
  true,
  -1,
  1,
  0,
  0
];

let expected2 = [
  false,
  false,
  true,
  true,
  -1,
  1,
  0,
  0
];

let u = [
  false,
  false,
  true,
  true,
  -1,
  1,
  0,
  0
];

function ff(x, y) {
  return Primitive_bool.min(x, y());
}

Mocha.describe("Gpr496_test", () => {
  Mocha.test("expected equals u", () => Test_utils.eq("File \"gpr496_test.res\", line 30, characters 37-44", expected, u));
  Mocha.test("expected equals expected2", () => Test_utils.eq("File \"gpr496_test.res\", line 31, characters 45-52", expected, expected2));
  Mocha.test("min function", () => Test_utils.eq("File \"gpr496_test.res\", line 32, characters 32-39", false, true < false));
});

export {
  expected,
  expected2,
  u,
  ff,
}
/*  Not a pure module */
