// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let result = {
  contents: ""
};

function log(x) {
  result.contents = x;
}

let Xx = {
  log: log
};

function compilerBug(a, b, c, f) {
  let exit = 0;
  if (a !== "x") {
    exit = 2;
  }
  if (exit === 2) {
    if (b === undefined) {
      if (c) {
        result.contents = "No x, c is true";
      } else {
        result.contents = "No x, c is false";
      }
      return;
    }
    if (b !== "x") {
      if (c) {
        result.contents = "No x, c is true";
      } else {
        result.contents = "No x, c is false";
      }
      return;
    }
    
  }
  if (f()) {
    result.contents = "Some x, f returns true";
  } else {
    result.contents = "Some x, f returns false";
  }
}

Mocha.describe("Gpr_3875_test", () => {
  Mocha.test("compiler bug pattern matching", () => {
    compilerBug("x", undefined, true, () => true);
    Test_utils.eq("File \"gpr_3875_test.res\", line 35, characters 7-14", result.contents, "Some x, f returns true");
  });
});

export {
  result,
  Xx,
  compilerBug,
}
/*  Not a pure module */
