// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let x = ({
  x: 3,
  y: 4
}).x;

let zz = ({
  _5: 3
})._5;

let h = {
  "0123": 2,
  "123_456": 3
};

function f(id) {
  while (false) {
    
  };
  return id;
}

Test_utils.eq("File \"gpr_1946_test.res\", line 23, characters 3-10", ({
  _5: 3
})._5, 3);

Test_utils.eq("File \"gpr_1946_test.res\", line 24, characters 3-10", [
  2,
  3
], [
  f(h)["0123"],
  f(h)["123_456"]
]);

console.log(({
    _5: 3
  }).TAG);

Mocha.describe("Gpr_1946_test", () => {
  Mocha.test("test1", () => Test_utils.eq("File \"gpr_1946_test.res\", line 29, characters 7-14", ({
    _5: 3
  })._5, 3));
  Mocha.test("test2", () => Test_utils.eq("File \"gpr_1946_test.res\", line 33, characters 7-14", [
    2,
    3
  ], [
    f(h)["0123"],
    f(h)["123_456"]
  ]));
});

export {
  x,
  zz,
  h,
  f,
}
/* x Not a pure module */
