// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function nextFor(x) {
  if (x !== undefined) {
    if (x === "Required") {
      return "Optional";
    } else {
      return;
    }
  } else {
    return "Required";
  }
}

Mocha.describe("Gpr_4519_test", () => {
  Mocha.test("option type pattern matching", () => Test_utils.eq("File \"gpr_4519_test.res\", line 17, characters 7-14", nextFor("Required"), "Optional"));
});

export {
  nextFor,
}
/*  Not a pure module */
