// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let v = {
  contents: 3
};

function update() {
  v.contents = v.contents + 1 | 0;
  return true;
}

v.contents = v.contents + 1 | 0;

Mocha.describe("Gpr_1762_test", () => {
  Mocha.test("gpr_1762 ref increment test", () => Test_utils.eq("File \"gpr_1762_test.res\", line 21, characters 7-14", v.contents, 4));
});

export {
  v,
  update,
}
/*  Not a pure module */
