// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Gpr_3566_test from "./gpr_3566_test.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let H = Gpr_3566_test.Test({});

let Caml_option = {};

function f(x) {
  return Primitive_option.some(x);
}

Mocha.describe("Gpr_3566_drive_test", () => {
  Mocha.test("gpr_3566_drive_test", () => Test_utils.eq("File \"gpr_3566_drive_test.res\", line 10, characters 39-46", H.b, true));
});

export {
  H,
  Caml_option,
  f,
}
/* H Not a pure module */
