// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "@rescript/runtime/lib/es6/Js_math.js";

if (1 !== 1) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "gpr_3980_test.res",
      15,
      7
    ],
    Error: new Error()
  };
}

let match = 1;

if (match !== 1) {
  if (match !== 2) {
    throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "gpr_3980_test.res",
        13,
        9
      ],
      Error: new Error()
    };
  }
  Js_math.floor(1);
}

/*  Not a pure module */
