// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let others = [
  0,
  0,
  1,
  1,
  2e3
];

Mocha.describe("Gpr_3549_test", () => {
  Mocha.test("numeric literal formatting test", () => {
    Test_utils.eq("File \"gpr_3549_test.res\", line 13, characters 7-14", 7.0, 7);
    Test_utils.eq("File \"gpr_3549_test.res\", line 14, characters 7-14", 2e3, 2000);
    Test_utils.eq("File \"gpr_3549_test.res\", line 15, characters 7-14", 0.2, 0.2);
    Test_utils.eq("File \"gpr_3549_test.res\", line 16, characters 7-14", 32, 32);
    Test_utils.eq("File \"gpr_3549_test.res\", line 17, characters 7-14", others, [
      0.0,
      0.0,
      1.0,
      1.0,
      2e3
    ]);
  });
});

let u = 32;

let x = 7.0;

let y = 2e3;

let z = 0.2;

export {
  u,
  x,
  y,
  z,
  others,
}
/*  Not a pure module */
