// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function foo(a){return a()}
;

function fn() {
  console.log("hi");
  return 1;
}

Mocha.describe("Gpr_3492_test", () => {
  Mocha.test("external function call", () => Test_utils.eq("File \"gpr_3492_test.res\", line 15, characters 7-14", foo(fn), 1));
});

export {
  fn,
}
/*  Not a pure module */
