// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let u = (function fib(n){
  if(n===0||n==1){
    return 1
  }
  return fib(n-1) + fib(n-2)
});

Mocha.describe("gpr_4442_test.res", () => {
  Mocha.test("gpr_4442_test", () => {
    Test_utils.eq("File \"gpr_4442_test.res\", line 13, characters 7-14", u(2), 2);
    Test_utils.eq("File \"gpr_4442_test.res\", line 14, characters 7-14", u(3), 3);
  });
});

export {
  u,
}
/*  Not a pure module */
