// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function f() {
  let x = new Date();
  let y = new Date();
  return [
    Primitive_object.greaterthan(y, x),
    Primitive_object.lessthan(y, x),
    true
  ];
}

Mocha.describe("Gpr_1817_test", () => {
  Mocha.test("date comparison test", () => {
    let match = f();
    console.log(match[0], match[1]);
    Test_utils.eq("File \"gpr_1817_test.res\", line 16, characters 7-14", match[2], true);
  });
});

export {
  f,
}
/*  Not a pure module */
