// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function fake_c2(a_type, b_type) {
  switch (a_type) {
    case "number" :
      if (b_type === "number") {
        return 33;
      }
      break;
    case "string" :
      return 1;
    case "undefined" :
      return -1;
  }
  if (b_type === "undefined") {
    return 1;
  } else if (a_type === "number") {
    return 3;
  } else {
    return 0;
  }
}

Mocha.describe("Gpr_2931_test", () => {
  Mocha.test("fake comparison function", () => Test_utils.eq("File \"gpr_2931_test.res\", line 16, characters 7-14", 3, fake_c2("number", "xx")));
});

export {
  fake_c2,
}
/*  Not a pure module */
