// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Belt_MutableMapInt from "@rescript/runtime/lib/es6/Belt_MutableMapInt.js";

let mockMap = Belt_MutableMapInt.make();

function add(id) {
  Belt_MutableMapInt.set(mockMap, id, id);
  return id;
}

function remove(id) {
  Belt_MutableMapInt.remove(mockMap, id);
}

add(1726);

let n = add(6667);

add(486);

Belt_MutableMapInt.remove(mockMap, 1726);

let n1 = Belt_MutableMapInt.getExn(mockMap, 6667);

Mocha.describe("Gpr_4265_test", () => {
  Mocha.test("mutable map operations", () => Test_utils.eq("File \"gpr_4265_test.res\", line 18, characters 42-49", n, n1));
});

export {
  mockMap,
  add,
  remove,
  n,
  n1,
}
/* mockMap Not a pure module */
