// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function check_healty(check) {
  if (!check.a && !check.b) {
    return !check.c;
  } else {
    return false;
  }
}

function basic_not(x) {
  return !x;
}

function f(check) {
  if (check.x) {
    return check.y;
  } else {
    return false;
  }
}

Mocha.describe("Gpr_904_test", () => {
  Mocha.test("f function", () => Test_utils.eq("File \"gpr_904_test.res\", line 12, characters 30-37", false, f({
    x: true,
    y: false
  })));
  Mocha.test("check_healty function", () => Test_utils.eq("File \"gpr_904_test.res\", line 14, characters 7-14", false, check_healty({
    a: false,
    b: false,
    c: true
  })));
});

export {
  check_healty,
  basic_not,
  f,
}
/*  Not a pure module */
