// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Gpr_1749_test", () => {
  Mocha.test("gpr_1749_test", () => Test_utils.eq("File \"gpr_1749_test.res\", line 12, characters 7-14", 0, 0));
});

/*  Not a pure module */
