// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(x) {
  for (let i = 0; i <= 100; ++i) {
    console.log(".");
  }
  return -x | 0;
}

let u = f(-2147483648);

Mocha.describe("Gpr_977_test", () => {
  Mocha.test("min 32 int function", () => Test_utils.eq("File \"gpr_977_test.res\", line 15, characters 39-46", -2147483648, u));
});

let min_32_int = -2147483648;

export {
  f,
  min_32_int,
  u,
}
/* u Not a pure module */
