// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Gpr_3595_test", () => {
  Mocha.test("commented out pattern test", () => Test_utils.eq("File \"gpr_3595_test.res\", line 13, characters 7-14", 1, 1));
});

let x = 1;

export {
  x,
}
/*  Not a pure module */
