// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Gpr_2789_test", () => {
  Mocha.test("weak array commented out tests", () => Test_utils.eq("File \"gpr_2789_test.res\", line 7, characters 7-14", 1, 1));
});

/*  Not a pure module */
