// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let uu = {
  "_'x": 3
};

let uu2 = {
  _then: 1,
  catch: 2,
  "_'x": 3
};

let hh = uu["_'x"];

Mocha.describe("Gpr_459_test", () => {
  Mocha.test("access object property with underscore", () => Test_utils.eq("File \"gpr_459_test.res\", line 19, characters 58-65", hh, 3));
  Mocha.test("access multiple object properties", () => Test_utils.eq("File \"gpr_459_test.res\", line 21, characters 7-14", [
    1,
    2,
    3
  ], [
    uu2._then,
    uu2.catch,
    uu2["_'x"]
  ]));
});

/* hh Not a pure module */
