// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Gpr_1822_test", () => {
  Mocha.test("gpr_1822_test", () => {
    let myShape = {
      TAG: "Circle",
      _0: 10
    };
    let area;
    area = myShape.TAG === "Circle" ? 100 * 3.14 : 10 * myShape._1 | 0;
    Test_utils.eq("File \"gpr_1822_test.res\", line 16, characters 7-14", area, 314);
  });
});

/*  Not a pure module */
