// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Gpr_1423_nav from "./gpr_1423_nav.mjs";

function foo(f) {
  console.log(f("a1", undefined));
}

foo((none, extra) => Gpr_1423_nav.busted(none, "a2", extra));

function foo2(f) {
  return f("a1", undefined);
}

Mocha.describe("Gpr_1423_app_test", () => {
  Mocha.test("gpr_1423_app_test", () => Test_utils.eq("File \"gpr_1423_app_test.res\", line 11, characters 37-44", Gpr_1423_nav.busted("a1", "a2", undefined), "a1a2"));
});

export {
  foo,
  foo2,
}
/*  Not a pure module */
