// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

Mocha.describe("Gpr_3154_test", () => {
  Mocha.test("Js.Dict None value handling", () => {
    let d = {};
    d["foo"] = undefined;
    let match = Js_dict.get(d, "foo");
    if (match !== undefined && Primitive_option.valFromOption(match) === undefined) {
      return Test_utils.ok("File \"gpr_3154_test.res\", line 11, characters 23-30", true);
    } else {
      return Test_utils.ok("File \"gpr_3154_test.res\", line 12, characters 14-21", false);
    }
  });
  Mocha.test("Js.Dict get with None", () => {
    let d0 = {};
    d0["foo"] = undefined;
    Test_utils.eq("File \"gpr_3154_test.res\", line 19, characters 7-14", Js_dict.get(d0, "foo"), Primitive_option.some(undefined));
  });
});

let J;

export {
  J,
}
/*  Not a pure module */
