// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let X = {};

function xx(obj, a0, a1, a2, a3, a4, a5) {
  return (a4(a2(a0(obj, a1), a3), a5) - 1 | 0) - 3 | 0;
}

Mocha.describe("Gpr_3536_test", () => {
  Mocha.test("method chaining with + operator", () => Test_utils.eq("File \"gpr_3536_test.res\", line 19, characters 7-14", 5, 5));
  Mocha.test("complex method chaining", () => Test_utils.eq("File \"gpr_3536_test.res\", line 23, characters 7-14", xx(3, (prim0, prim1) => prim0 - prim1 | 0, 2, (prim0, prim1) => prim0 + prim1 | 0, 4, (prim0, prim1) => prim0 * prim1 | 0, 3), 11));
});

let v = 5;

let u = {
  TAG: "Some",
  _0: 3
};

export {
  v,
  X,
  u,
  xx,
}
/*  Not a pure module */
