// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let a = {};

let b = {};

Primitive_object.updateDummy(a, {
  b: b
});

Primitive_object.updateDummy(b, {
  a: a
});

function is_inifite(x) {
  return x.b.a === x;
}

Mocha.describe("Gpr_1716_test", () => {
  Mocha.test("recursive type infinite loop", () => Test_utils.eq("File \"gpr_1716_test.res\", line 13, characters 7-14", true, is_inifite(a)));
});

export {
  a,
  b,
  is_inifite,
}
/*  Not a pure module */
