// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Gpr_1667_test", () => {
  Mocha.test("gpr 1667 test", () => Test_utils.eq("File \"gpr_1667_test.res\", line 21, characters 7-14", 0, 0));
});

/*  Not a pure module */
