// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function testIdentity(x) {
  if (x.NAME === 2) {
    return {
      NAME: 2,
      VAL: x.VAL
    };
  } else {
    return {
      NAME: 1,
      VAL: x.VAL
    };
  }
}

Mocha.describe("Gpr_5218_test", () => {
  Mocha.test("polymorphic variant identity test", () => {
    Test_utils.eq("File \"gpr_5218_test.res\", line 12, characters 7-14", testIdentity({
      NAME: 1,
      VAL: 3
    }), {
      NAME: 1,
      VAL: 3
    });
    Test_utils.eq("File \"gpr_5218_test.res\", line 13, characters 7-14", testIdentity({
      NAME: 2,
      VAL: 3
    }), {
      NAME: 2,
      VAL: 3
    });
  });
});

export {
  testIdentity,
}
/*  Not a pure module */
