// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(x) {
  return [
    x._003,
    x._50,
    x._50x,
    x.__50,
    x.__50x,
    x["_50x'"],
    x["x'"]
  ];
}

Mocha.describe("Gpr_1943_test", () => {
  Mocha.test("object property access with special characters", () => {
    let v = f({
      _003: 0,
      _50: 1,
      _50x: 2,
      __50: 3,
      __50x: 4,
      "_50x'": 5,
      "x'": 6
    });
    Test_utils.eq("File \"gpr_1943_test.res\", line 19, characters 7-14", [
      0,
      1,
      2,
      3,
      4,
      5,
      6
    ], v);
  });
});

export {
  f,
}
/*  Not a pure module */
