// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

Mocha.describe("Gpr_1760_test", () => {
  Mocha.test("division by zero exception handling", () => {
    let a0;
    try {
      Primitive_int.div(0, 0);
      a0 = 0;
    } catch (exn) {
      a0 = 1;
    }
    let a1;
    try {
      Primitive_int.mod_(0, 0);
      a1 = 0;
    } catch (exn$1) {
      a1 = 1;
    }
    Test_utils.eq("File \"gpr_1760_test.res\", line 20, characters 7-14", [
      a0,
      a1
    ], [
      1,
      1
    ]);
  });
});

/*  Not a pure module */
