// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Gpr_4900_test", () => {
  Mocha.test("gpr_4900_test", () => {
    Test_utils.eq("File \"gpr_4900_test.res\", line 14, characters 7-14", true, true);
    Test_utils.eq("File \"gpr_4900_test.res\", line 15, characters 7-14", false, false);
    Test_utils.eq("File \"gpr_4900_test.res\", line 16, characters 7-14", true, true);
  });
});

/*  Not a pure module */
