// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_List from "@rescript/runtime/lib/es6/Belt_List.js";
import * as Test_utils from "./test_utils.mjs";

let oppHeroes = {
  hd: 0,
  tl: /* [] */0
};

let huntGrootCondition = false;

if (Belt_List.length(/* [] */0) > 0) {
  let x = Belt_List.filter(oppHeroes, h => Belt_List.headExn(/* [] */0) <= 1000);
  huntGrootCondition = Belt_List.length(x) === 0;
}

let huntGrootCondition2 = true;

if (Belt_List.length(/* [] */0) < 0) {
  let x$1 = Belt_List.filter(oppHeroes, h => Belt_List.headExn(/* [] */0) <= 1000);
  huntGrootCondition2 = Belt_List.length(x$1) === 0;
}

Mocha.describe("Gpr_2608_test", () => {
  Mocha.test("huntGroot conditions", () => {
    Test_utils.eq("File \"gpr_2608_test.res\", line 22, characters 7-14", huntGrootCondition, false);
    Test_utils.eq("File \"gpr_2608_test.res\", line 23, characters 7-14", huntGrootCondition2, true);
  });
});

let nearestGroots = /* [] */0;

export {
  nearestGroots,
  oppHeroes,
  huntGrootCondition,
  huntGrootCondition2,
}
/* huntGrootCondition Not a pure module */
