// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let y;

try {
  Pervasives.failwith("boo");
  y = undefined;
} catch (raw_msg) {
  let msg = Primitive_exceptions.internalToException(raw_msg);
  if (msg.RE_EXN_ID === "Failure") {
    y = msg._1;
  } else {
    throw msg;
  }
}

let x;

let exit = 0;

let e;

try {
  e = Pervasives.failwith("boo");
  exit = 1;
} catch (raw_msg$1) {
  let msg$1 = Primitive_exceptions.internalToException(raw_msg$1);
  if (msg$1.RE_EXN_ID === "Failure") {
    x = msg$1._1;
  } else {
    throw msg$1;
  }
}

if (exit === 1) {
  console.log("ok");
  x = undefined;
}

Mocha.describe("Gpr_2316_test", () => {
  Mocha.test("gpr_2316_test", () => {
    Test_utils.eq("File \"gpr_2316_test.res\", line 18, characters 7-14", y, "boo");
    Test_utils.eq("File \"gpr_2316_test.res\", line 19, characters 7-14", x, "boo");
  });
});

export {
  y,
  x,
}
/* y Not a pure module */
