// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Js_types from "@rescript/runtime/lib/es6/Js_types.js";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("File \"gpr_1658_test.res\", line 4, characters 9-16", () => {
  Mocha.test("JS Null operations", () => {
    Test_utils.eq("File \"gpr_1658_test.res\", line 6, characters 7-14", null, null);
    let match = Js_types.classify(null);
    if (typeof match !== "object" && match === "JSNull") {
      Test_utils.eq("File \"gpr_1658_test.res\", line 8, characters 19-26", true, true);
    } else {
      Test_utils.eq("File \"gpr_1658_test.res\", line 9, characters 14-21", true, false);
    }
    Test_utils.eq("File \"gpr_1658_test.res\", line 11, characters 7-14", true, Js_types.test(null, "Null"));
  });
});

/*  Not a pure module */
