// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Gpr_4924_test", () => {
  Mocha.test("gpr_4924_test", () => {
    Test_utils.eq("File \"gpr_4924_test.res\", line 29, characters 7-14", false, false);
    Test_utils.eq("File \"gpr_4924_test.res\", line 30, characters 7-14", true, true);
    Test_utils.eq("File \"gpr_4924_test.res\", line 31, characters 7-14", true, true);
  });
});

/*  Not a pure module */
