// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f0(x) {
  if (x === "azdwbie") {
    return 1;
  } else {
    return 0;
  }
}

function f1(x) {
  if (x.NAME === "azdwbie") {
    return x.VAL + 2 | 0;
  } else {
    return x.VAL + 1 | 0;
  }
}

Mocha.describe("Hash_collision_test", () => {
  Mocha.test("hash collision variants", () => {
    Test_utils.eq("File \"hash_collision_test.res\", line 21, characters 7-14", 0, 0);
    Test_utils.eq("File \"hash_collision_test.res\", line 22, characters 7-14", 1, 1);
    Test_utils.eq("File \"hash_collision_test.res\", line 23, characters 7-14", f1({
      NAME: "Eric_Cooper",
      VAL: -1
    }), 0);
    Test_utils.eq("File \"hash_collision_test.res\", line 24, characters 7-14", f1({
      NAME: "azdwbie",
      VAL: -2
    }), 0);
  });
});

export {
  f0,
  f1,
}
/*  Not a pure module */
