// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Hash_utils from "./hash_utils.mjs";
import * as Test_utils from "./test_utils.mjs";

let test_strings = Belt_Array.init(32, i => String.fromCodePoint(i).repeat(i));

let test_strings_hash_results = [
  0,
  904391063,
  889600889,
  929588010,
  596566298,
  365199070,
  448044845,
  311625091,
  681445541,
  634941451,
  82108334,
  17482990,
  491949228,
  696194769,
  711728152,
  594966620,
  820561748,
  958901713,
  102794744,
  378848504,
  349314368,
  114167579,
  71240932,
  110067399,
  280623927,
  323523937,
  310683234,
  178511779,
  585018975,
  544388424,
  1043872806,
  831138595
];

function normalize(x) {
  return x & 1073741823;
}

function caml_hash(x) {
  return Hash_utils.hash(x) & 1073741823;
}

Mocha.describe("Hash_test", () => {
  Mocha.test("test strings hash results", () => Test_utils.eq("File \"hash_test.res\", line 47, characters 7-14", Belt_Array.map(test_strings, caml_hash), test_strings_hash_results));
  Mocha.test("hash 0", () => Test_utils.eq("File \"hash_test.res\", line 51, characters 7-14", Hash_utils.hash(0) & 1073741823, 129913994));
  Mocha.test("hash x", () => Test_utils.eq("File \"hash_test.res\", line 55, characters 7-14", Hash_utils.hash("x") & 1073741823, 780510073));
  Mocha.test("hash xy", () => Test_utils.eq("File \"hash_test.res\", line 59, characters 7-14", Hash_utils.hash("xy") & 1073741823, 194127723));
});

export {
  test_strings,
  test_strings_hash_results,
  normalize,
  caml_hash,
}
/* test_strings Not a pure module */
