// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(x) {
  
}

function ff(x) {
  console.log(x);
}

Mocha.describe("Ignore_test", () => {
  Mocha.test("ignore function", () => Test_utils.eq("File \"ignore_test.res\", line 10, characters 7-14", undefined, undefined));
});

export {
  f,
  ff,
}
/*  Not a pure module */
