// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Inline_const from "./inline_const.mjs";

let H = Inline_const.N1({});

let f = "hello";

let f1 = `a`;

let f2 = `中文`;

let f3 = `中文`;

let f4 = `中文`;

Mocha.describe("File \"inline_const_test.res\", line 11, characters 9-16", () => {
  Mocha.test("inline const test", () => {
    Test_utils.eq("File \"inline_const_test.res\", line 13, characters 7-14", f, "hello");
    Test_utils.eq("File \"inline_const_test.res\", line 14, characters 7-14", f1, "a");
    Test_utils.eq("File \"inline_const_test.res\", line 15, characters 7-14", f2, `中文`);
    Test_utils.eq("File \"inline_const_test.res\", line 16, characters 7-14", f3, `中文`);
    Test_utils.eq("File \"inline_const_test.res\", line 17, characters 7-14", f4, `中文`);
    Test_utils.eq("File \"inline_const_test.res\", line 18, characters 7-14", true, true);
    Test_utils.eq("File \"inline_const_test.res\", line 19, characters 7-14", 1, 1);
    Test_utils.eq("File \"inline_const_test.res\", line 20, characters 7-14", 3e-6, 0.000003);
  });
});

let f5 = true;

let f6 = 1;

let f7 = 3e-6;

export {
  H,
  f,
  f1,
  f2,
  f3,
  f4,
  f5,
  f6,
  f7,
}
/* H Not a pure module */
