// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(x) {
  let match = x();
  switch (match) {
    case 1 :
      return /* 'a' */97;
    case 2 :
      return /* 'b' */98;
    case 3 :
      return /* 'c' */99;
    default:
      return /* 'x' */120;
  }
}

function f22(x) {
  let match = x();
  switch (match) {
    case 1 :
      return /* 'a' */97;
    case 2 :
      return /* 'b' */98;
    case 3 :
      return /* 'c' */99;
    default:
      return /* 'x' */120;
  }
}

function f33(x) {
  let match = x();
  switch (match) {
    case "A" :
      return /* 'a' */97;
    case "B" :
      return /* 'b' */98;
    case "C" :
      return /* 'c' */99;
    case "D" :
      return /* 'x' */120;
  }
}

Mocha.describe("Int_switch_test", () => {
  Mocha.test("integer switch function", () => {
    Test_utils.eq("File \"int_switch_test.res\", line 32, characters 7-14", f(() => 1), /* 'a' */97);
    Test_utils.eq("File \"int_switch_test.res\", line 33, characters 7-14", f(() => 2), /* 'b' */98);
    Test_utils.eq("File \"int_switch_test.res\", line 34, characters 7-14", f(() => 3), /* 'c' */99);
    Test_utils.eq("File \"int_switch_test.res\", line 35, characters 7-14", f(() => 0), /* 'x' */120);
    Test_utils.eq("File \"int_switch_test.res\", line 36, characters 7-14", f(() => -1), /* 'x' */120);
  });
});

export {
  f,
  f22,
  f33,
}
/*  Not a pure module */
