// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(x) {
  return x;
}

function f2(x) {
  return x;
}

function f4(x) {
  return x;
}

let u = (!!1);

let v = true;

function ff(u) {
  if (u === true) {
    return 1;
  } else {
    return 2;
  }
}

function fi(x, y) {
  return x === y;
}

function fb(x, y) {
  return x === y;
}

function fadd(x, y) {
  return x + y | 0;
}

function ffadd(x, y) {
  return x + y;
}

function ss(x) {
  return "xx" > x;
}

function bb(x) {
  return [
    true > x,
    false,
    true,
    true <= x,
    false,
    false < x,
    false >= x,
    true
  ];
}

let consts = [
  false,
  false,
  true,
  false,
  true,
  false,
  true,
  true
];

let bool_array = [
  true,
  false
];

Mocha.describe("Js_bool_test", () => {
  Mocha.test("?bool_eq_caml_bool", () => Test_utils.eq("File \"js_bool_test.res\", line 74, characters 38-45", u, true));
  Mocha.test("js_bool_eq_js_bool", () => Test_utils.eq("File \"js_bool_test.res\", line 75, characters 38-45", v, true));
  Mocha.test("js_bool_neq_acml_bool", () => Test_utils.ok("File \"js_bool_test.res\", line 76, characters 41-48", true === true));
});

let f3 = true;

export {
  f,
  f2,
  f4,
  f3,
  u,
  v,
  ff,
  fi,
  fb,
  fadd,
  ffadd,
  ss,
  bb,
  consts,
  bool_array,
}
/* u Not a pure module */
