// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function date() {
  return new Date("1976-03-08T12:34:56.789+01:23");
}

Mocha.describe("Js_date_test", () => {
  Mocha.test("valueOf", () => Test_utils.eq("File \"js_date_test.res\", line 9, characters 27-34", 195131516789, new Date("1976-03-08T12:34:56.789+01:23").valueOf()));
  Mocha.test("make", () => Test_utils.eq("File \"js_date_test.res\", line 10, characters 24-31", true, new Date().getTime() > 1487223505382));
  Mocha.test("parseAsFloat", () => Test_utils.eq("File \"js_date_test.res\", line 12, characters 7-14", Date.parse("1976-03-08T12:34:56.789+01:23"), 195131516789));
  Mocha.test("parseAsFloat_invalid", () => Test_utils.eq("File \"js_date_test.res\", line 14, characters 40-47", true, Number.isNaN(Date.parse("gibberish"))));
  Mocha.test("fromFloat", () => Test_utils.eq("File \"js_date_test.res\", line 16, characters 7-14", "1976-03-08T11:11:56.789Z", new Date(195131516789).toISOString()));
  Mocha.test("fromString_valid", () => Test_utils.eq("File \"js_date_test.res\", line 19, characters 7-14", 195131516789, new Date("1976-03-08T12:34:56.789+01:23").getTime()));
  Mocha.test("fromString_invalid", () => Test_utils.eq("File \"js_date_test.res\", line 22, characters 7-14", true, Number.isNaN(new Date("gibberish").getTime())));
  Mocha.test("makeWithYM", () => {
    let d = new Date(1984, 4);
    Test_utils.eq("File \"js_date_test.res\", line 26, characters 7-14", [
      1984,
      4
    ], [
      d.getFullYear(),
      d.getMonth()
    ]);
  });
  Mocha.test("makeWithYMD", () => {
    let d = new Date(1984, 4, 6);
    Test_utils.eq("File \"js_date_test.res\", line 30, characters 7-14", [
      1984,
      4,
      6
    ], [
      d.getFullYear(),
      d.getMonth(),
      d.getDate()
    ]);
  });
  Mocha.test("makeWithYMDH", () => {
    let d = new Date(1984, 4, 6, 3);
    Test_utils.eq("File \"js_date_test.res\", line 34, characters 7-14", [
      1984,
      4,
      6,
      3
    ], [
      d.getFullYear(),
      d.getMonth(),
      d.getDate(),
      d.getHours()
    ]);
  });
  Mocha.test("makeWithYMDHM", () => {
    let d = new Date(1984, 4, 6, 3, 59);
    Test_utils.eq("File \"js_date_test.res\", line 39, characters 6-13", [
      1984,
      4,
      6,
      3,
      59
    ], [
      d.getFullYear(),
      d.getMonth(),
      d.getDate(),
      d.getHours(),
      d.getMinutes()
    ]);
  });
  Mocha.test("makeWithYMDHMS", () => {
    let d = new Date(1984, 4, 6, 3, 59, 27);
    Test_utils.eq("File \"js_date_test.res\", line 55, characters 6-13", [
      1984,
      4,
      6,
      3,
      59,
      27
    ], [
      d.getFullYear(),
      d.getMonth(),
      d.getDate(),
      d.getHours(),
      d.getMinutes(),
      d.getSeconds()
    ]);
  });
  Mocha.test("utcWithYM", () => {
    let d = Date.UTC(1984, 4);
    let d$1 = new Date(d);
    Test_utils.eq("File \"js_date_test.res\", line 70, characters 7-14", [
      1984,
      4
    ], [
      d$1.getUTCFullYear(),
      d$1.getUTCMonth()
    ]);
  });
  Mocha.test("utcWithYMD", () => {
    let d = Date.UTC(1984, 4, 6);
    let d$1 = new Date(d);
    Test_utils.eq("File \"js_date_test.res\", line 75, characters 7-14", [
      1984,
      4,
      6
    ], [
      d$1.getUTCFullYear(),
      d$1.getUTCMonth(),
      d$1.getUTCDate()
    ]);
  });
  Mocha.test("utcWithYMDH", () => {
    let d = Date.UTC(1984, 4, 6, 3);
    let d$1 = new Date(d);
    Test_utils.eq("File \"js_date_test.res\", line 81, characters 6-13", [
      1984,
      4,
      6,
      3
    ], [
      d$1.getUTCFullYear(),
      d$1.getUTCMonth(),
      d$1.getUTCDate(),
      d$1.getUTCHours()
    ]);
  });
  Mocha.test("utcWithYMDHM", () => {
    let d = Date.UTC(1984, 4, 6, 3, 59);
    let d$1 = new Date(d);
    Test_utils.eq("File \"js_date_test.res\", line 90, characters 6-13", [
      1984,
      4,
      6,
      3,
      59
    ], [
      d$1.getUTCFullYear(),
      d$1.getUTCMonth(),
      d$1.getUTCDate(),
      d$1.getUTCHours(),
      d$1.getUTCMinutes()
    ]);
  });
  Mocha.test("utcWithYMDHMS", () => {
    let d = Date.UTC(1984, 4, 6, 3, 59, 27);
    let d$1 = new Date(d);
    Test_utils.eq("File \"js_date_test.res\", line 113, characters 6-13", [
      1984,
      4,
      6,
      3,
      59,
      27
    ], [
      d$1.getUTCFullYear(),
      d$1.getUTCMonth(),
      d$1.getUTCDate(),
      d$1.getUTCHours(),
      d$1.getUTCMinutes(),
      d$1.getUTCSeconds()
    ]);
  });
  Mocha.test("getFullYear", () => Test_utils.eq("File \"js_date_test.res\", line 125, characters 31-38", 1976, new Date("1976-03-08T12:34:56.789+01:23").getFullYear()));
  Mocha.test("getMilliseconds", () => Test_utils.eq("File \"js_date_test.res\", line 126, characters 35-42", 789, new Date("1976-03-08T12:34:56.789+01:23").getMilliseconds()));
  Mocha.test("getSeconds", () => Test_utils.eq("File \"js_date_test.res\", line 127, characters 30-37", 56, new Date("1976-03-08T12:34:56.789+01:23").getSeconds()));
  Mocha.test("getTime", () => Test_utils.eq("File \"js_date_test.res\", line 128, characters 27-34", 195131516789, new Date("1976-03-08T12:34:56.789+01:23").getTime()));
  Mocha.test("getUTCDate", () => Test_utils.eq("File \"js_date_test.res\", line 129, characters 30-37", 8, new Date("1976-03-08T12:34:56.789+01:23").getUTCDate()));
  Mocha.test("getUTCDay", () => Test_utils.eq("File \"js_date_test.res\", line 130, characters 29-36", 1, new Date("1976-03-08T12:34:56.789+01:23").getUTCDay()));
  Mocha.test("getUTCFUllYear", () => Test_utils.eq("File \"js_date_test.res\", line 131, characters 34-41", 1976, new Date("1976-03-08T12:34:56.789+01:23").getUTCFullYear()));
  Mocha.test("getUTCHours", () => Test_utils.eq("File \"js_date_test.res\", line 132, characters 31-38", 11, new Date("1976-03-08T12:34:56.789+01:23").getUTCHours()));
  Mocha.test("getUTCMilliseconds", () => Test_utils.eq("File \"js_date_test.res\", line 133, characters 38-45", 789, new Date("1976-03-08T12:34:56.789+01:23").getUTCMilliseconds()));
  Mocha.test("getUTCMinutes", () => Test_utils.eq("File \"js_date_test.res\", line 134, characters 33-40", 11, new Date("1976-03-08T12:34:56.789+01:23").getUTCMinutes()));
  Mocha.test("getUTCMonth", () => Test_utils.eq("File \"js_date_test.res\", line 135, characters 31-38", 2, new Date("1976-03-08T12:34:56.789+01:23").getUTCMonth()));
  Mocha.test("getUTCSeconds", () => Test_utils.eq("File \"js_date_test.res\", line 136, characters 33-40", 56, new Date("1976-03-08T12:34:56.789+01:23").getUTCSeconds()));
  Mocha.test("getYear", () => Test_utils.eq("File \"js_date_test.res\", line 137, characters 27-34", 1976, new Date("1976-03-08T12:34:56.789+01:23").getFullYear()));
  Mocha.test("setDate", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setDate(12);
    Test_utils.eq("File \"js_date_test.res\", line 141, characters 7-14", 12, d.getDate());
  });
  Mocha.test("setFullYear", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setFullYear(1986);
    Test_utils.eq("File \"js_date_test.res\", line 146, characters 7-14", 1986, d.getFullYear());
  });
  Mocha.test("setFullYearM", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setFullYear(1986, 7);
    Test_utils.eq("File \"js_date_test.res\", line 151, characters 7-14", [
      1986,
      7
    ], [
      d.getFullYear(),
      d.getMonth()
    ]);
  });
  Mocha.test("setFullYearMD", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setFullYear(1986, 7, 23);
    Test_utils.eq("File \"js_date_test.res\", line 156, characters 7-14", [
      1986,
      7,
      23
    ], [
      d.getFullYear(),
      d.getMonth(),
      d.getDate()
    ]);
  });
  Mocha.test("setHours", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setHours(22);
    Test_utils.eq("File \"js_date_test.res\", line 161, characters 7-14", 22, d.getHours());
  });
  Mocha.test("setHoursM", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setHours(22, 48);
    Test_utils.eq("File \"js_date_test.res\", line 166, characters 7-14", [
      22,
      48
    ], [
      d.getHours(),
      d.getMinutes()
    ]);
  });
  Mocha.test("setHoursMS", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setHours(22, 48, 54);
    Test_utils.eq("File \"js_date_test.res\", line 171, characters 7-14", [
      22,
      48,
      54
    ], [
      d.getHours(),
      d.getMinutes(),
      d.getSeconds()
    ]);
  });
  Mocha.test("setMilliseconds", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setMilliseconds(543);
    Test_utils.eq("File \"js_date_test.res\", line 176, characters 7-14", 543, d.getMilliseconds());
  });
  Mocha.test("setMinutes", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setMinutes(18);
    Test_utils.eq("File \"js_date_test.res\", line 181, characters 7-14", 18, d.getMinutes());
  });
  Mocha.test("setMinutesS", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setMinutes(18, 42);
    Test_utils.eq("File \"js_date_test.res\", line 186, characters 7-14", [
      18,
      42
    ], [
      d.getMinutes(),
      d.getSeconds()
    ]);
  });
  Mocha.test("setMinutesSMs", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setMinutes(18, 42, 311);
    Test_utils.eq("File \"js_date_test.res\", line 191, characters 7-14", [
      18,
      42,
      311
    ], [
      d.getMinutes(),
      d.getSeconds(),
      d.getMilliseconds()
    ]);
  });
  Mocha.test("setMonth", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setMonth(10);
    Test_utils.eq("File \"js_date_test.res\", line 196, characters 7-14", 10, d.getMonth());
  });
  Mocha.test("setMonthD", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setMonth(10, 14);
    Test_utils.eq("File \"js_date_test.res\", line 201, characters 7-14", [
      10,
      14
    ], [
      d.getMonth(),
      d.getDate()
    ]);
  });
  Mocha.test("setSeconds", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setSeconds(36);
    Test_utils.eq("File \"js_date_test.res\", line 206, characters 7-14", 36, d.getSeconds());
  });
  Mocha.test("setSecondsMs", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setSeconds(36, 420);
    Test_utils.eq("File \"js_date_test.res\", line 211, characters 7-14", [
      36,
      420
    ], [
      d.getSeconds(),
      d.getMilliseconds()
    ]);
  });
  Mocha.test("setUTCDate", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCDate(12);
    Test_utils.eq("File \"js_date_test.res\", line 216, characters 7-14", 12, d.getUTCDate());
  });
  Mocha.test("setUTCFullYear", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCFullYear(1986);
    Test_utils.eq("File \"js_date_test.res\", line 221, characters 7-14", 1986, d.getUTCFullYear());
  });
  Mocha.test("setUTCFullYearM", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCFullYear(1986, 7);
    Test_utils.eq("File \"js_date_test.res\", line 226, characters 7-14", [
      1986,
      7
    ], [
      d.getUTCFullYear(),
      d.getUTCMonth()
    ]);
  });
  Mocha.test("setUTCFullYearMD", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCFullYear(1986, 7, 23);
    Test_utils.eq("File \"js_date_test.res\", line 231, characters 7-14", [
      1986,
      7,
      23
    ], [
      d.getUTCFullYear(),
      d.getUTCMonth(),
      d.getUTCDate()
    ]);
  });
  Mocha.test("setUTCHours", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCHours(22);
    Test_utils.eq("File \"js_date_test.res\", line 236, characters 7-14", 22, d.getUTCHours());
  });
  Mocha.test("setUTCHoursM", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCHours(22, 48);
    Test_utils.eq("File \"js_date_test.res\", line 241, characters 7-14", [
      22,
      48
    ], [
      d.getUTCHours(),
      d.getUTCMinutes()
    ]);
  });
  Mocha.test("setUTCHoursMS", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCHours(22, 48, 54);
    Test_utils.eq("File \"js_date_test.res\", line 246, characters 7-14", [
      22,
      48,
      54
    ], [
      d.getUTCHours(),
      d.getUTCMinutes(),
      d.getUTCSeconds()
    ]);
  });
  Mocha.test("setUTCMilliseconds", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCMilliseconds(543);
    Test_utils.eq("File \"js_date_test.res\", line 251, characters 7-14", 543, d.getUTCMilliseconds());
  });
  Mocha.test("setUTCMinutes", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCMinutes(18);
    Test_utils.eq("File \"js_date_test.res\", line 256, characters 7-14", 18, d.getUTCMinutes());
  });
  Mocha.test("setUTCMinutesS", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCMinutes(18, 42);
    Test_utils.eq("File \"js_date_test.res\", line 261, characters 7-14", [
      18,
      42
    ], [
      d.getUTCMinutes(),
      d.getUTCSeconds()
    ]);
  });
  Mocha.test("setUTCMinutesSMs", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCMinutes(18, 42, 311);
    Test_utils.eq("File \"js_date_test.res\", line 266, characters 7-14", [
      18,
      42,
      311
    ], [
      d.getUTCMinutes(),
      d.getUTCSeconds(),
      d.getUTCMilliseconds()
    ]);
  });
  Mocha.test("setUTCMonth", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCMonth(10);
    Test_utils.eq("File \"js_date_test.res\", line 271, characters 7-14", 10, d.getUTCMonth());
  });
  Mocha.test("setUTCMonthD", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCMonth(10, 14);
    Test_utils.eq("File \"js_date_test.res\", line 276, characters 7-14", [
      10,
      14
    ], [
      d.getUTCMonth(),
      d.getUTCDate()
    ]);
  });
  Mocha.test("setUTCSeconds", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCSeconds(36);
    Test_utils.eq("File \"js_date_test.res\", line 281, characters 7-14", 36, d.getUTCSeconds());
  });
  Mocha.test("setUTCSecondsMs", () => {
    let d = new Date("1976-03-08T12:34:56.789+01:23");
    d.setUTCSeconds(36, 420);
    Test_utils.eq("File \"js_date_test.res\", line 286, characters 7-14", [
      36,
      420
    ], [
      d.getUTCSeconds(),
      d.getUTCMilliseconds()
    ]);
  });
  Mocha.test("toDateString", () => Test_utils.eq("File \"js_date_test.res\", line 288, characters 32-39", "Mon Mar 08 1976", new Date("1976-03-08T12:34:56.789+01:23").toDateString()));
  Mocha.test("toGMTString", () => Test_utils.eq("File \"js_date_test.res\", line 289, characters 31-38", "Mon, 08 Mar 1976 11:11:56 GMT", new Date("1976-03-08T12:34:56.789+01:23").toUTCString()));
  Mocha.test("toISOString", () => Test_utils.eq("File \"js_date_test.res\", line 290, characters 31-38", "1976-03-08T11:11:56.789Z", new Date("1976-03-08T12:34:56.789+01:23").toISOString()));
  Mocha.test("toJSON", () => Test_utils.eq("File \"js_date_test.res\", line 291, characters 26-33", "1976-03-08T11:11:56.789Z", new Date("1976-03-08T12:34:56.789+01:23").toJSON()));
  Mocha.test("toJSONUnsafe", () => Test_utils.eq("File \"js_date_test.res\", line 292, characters 32-39", "1976-03-08T11:11:56.789Z", new Date("1976-03-08T12:34:56.789+01:23").toJSON()));
  Mocha.test("toUTCString", () => Test_utils.eq("File \"js_date_test.res\", line 293, characters 31-38", "Mon, 08 Mar 1976 11:11:56 GMT", new Date("1976-03-08T12:34:56.789+01:23").toUTCString()));
  Mocha.test("eq", () => {
    let a = new Date("2013-03-01T01:10:00");
    let b = new Date("2013-03-01T01:10:00");
    let c = new Date("2013-03-01T01:10:01");
    Test_utils.ok("File \"js_date_test.res\", line 298, characters 7-14", Primitive_object.equal(a, b) && Primitive_object.notequal(b, c) && Primitive_object.greaterthan(c, b));
  });
});

let N;

export {
  N,
  date,
}
/*  Not a pure module */
