// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Js_global_test", () => {
  Mocha.test("setTimeout/clearTimeout sanity check", () => {
    let handle = setTimeout(() => {}, 0);
    clearTimeout(handle);
    Test_utils.eq("File \"js_global_test.res\", line 9, characters 7-14", true, true);
  });
  Mocha.test("setInterval/clearInterval sanity check", () => {
    let handle = setInterval(() => {}, 0);
    clearInterval(handle);
    Test_utils.eq("File \"js_global_test.res\", line 14, characters 7-14", true, true);
  });
  Mocha.test("encodeURI", () => Test_utils.eq("File \"js_global_test.res\", line 17, characters 7-14", "%5B-=-%5D", encodeURI("[-=-]")));
  Mocha.test("decodeURI", () => Test_utils.eq("File \"js_global_test.res\", line 20, characters 7-14", "[-=-]", decodeURI("%5B-=-%5D")));
  Mocha.test("encodeURIComponent", () => Test_utils.eq("File \"js_global_test.res\", line 23, characters 7-14", "%5B-%3D-%5D", encodeURIComponent("[-=-]")));
  Mocha.test("decodeURIComponent", () => Test_utils.eq("File \"js_global_test.res\", line 26, characters 7-14", "[-=-]", decodeURIComponent("%5B-%3D-%5D")));
});

/*  Not a pure module */
