// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Js_int_test", () => {
  Mocha.test("toExponential", () => Test_utils.eq("File \"js_int_test.res\", line 7, characters 7-14", "1.23456e+5", (123456).toExponential()));
  Mocha.test("toExponentialWithPrecision - digits:2", () => Test_utils.eq("File \"js_int_test.res\", line 11, characters 7-14", "1.23e+5", (123456).toExponential(2)));
  Mocha.test("toExponentialWithPrecision - digits:4", () => Test_utils.eq("File \"js_int_test.res\", line 15, characters 7-14", "1.2346e+5", (123456).toExponential(4)));
  Mocha.test("toExponentialWithPrecision - digits:20", () => Test_utils.eq("File \"js_int_test.res\", line 19, characters 7-14", "0.00000000000000000000e+0", (0).toExponential(20)));
  Mocha.test("toExponentialWithPrecision - digits:101 throws", () => Test_utils.throws("File \"js_int_test.res\", line 23, characters 11-18", () => {
    (0).toExponential(101);
  }));
  Mocha.test("toExponentialWithPrecision - digits:-1 throws", () => Test_utils.throws("File \"js_int_test.res\", line 27, characters 11-18", () => {
    (0).toExponential(-1);
  }));
  Mocha.test("toPrecision", () => Test_utils.eq("File \"js_int_test.res\", line 31, characters 7-14", "123456", (123456).toPrecision()));
  Mocha.test("toPrecisionWithPrecision - digits:2", () => Test_utils.eq("File \"js_int_test.res\", line 35, characters 7-14", "1.2e+5", (123456).toPrecision(2)));
  Mocha.test("toPrecisionWithPrecision - digits:4", () => Test_utils.eq("File \"js_int_test.res\", line 39, characters 7-14", "1.235e+5", (123456).toPrecision(4)));
  Mocha.test("toPrecisionWithPrecision - digits:20", () => Test_utils.eq("File \"js_int_test.res\", line 43, characters 7-14", "0.0000000000000000000", (0).toPrecision(20)));
  Mocha.test("toPrecisionWithPrecision - digits:101 throws", () => Test_utils.throws("File \"js_int_test.res\", line 47, characters 11-18", () => {
    (0).toPrecision(101);
  }));
  Mocha.test("toPrecisionWithPrecision - digits:-1 throws", () => Test_utils.throws("File \"js_int_test.res\", line 51, characters 11-18", () => {
    (0).toPrecision(-1);
  }));
  Mocha.test("toString", () => Test_utils.eq("File \"js_int_test.res\", line 55, characters 7-14", "123", (123).toString()));
  Mocha.test("toStringWithRadix - radix:2", () => Test_utils.eq("File \"js_int_test.res\", line 59, characters 7-14", "11110001001000000", (123456).toString(2)));
  Mocha.test("toStringWithRadix - radix:16", () => Test_utils.eq("File \"js_int_test.res\", line 63, characters 7-14", "1e240", (123456).toString(16)));
  Mocha.test("toStringWithRadix - radix:36", () => Test_utils.eq("File \"js_int_test.res\", line 67, characters 7-14", "2n9c", (123456).toString(36)));
  Mocha.test("toStringWithRadix - radix:37 throws", () => Test_utils.throws("File \"js_int_test.res\", line 71, characters 11-18", () => {
    (0).toString(37);
  }));
  Mocha.test("toStringWithRadix - radix:1 throws", () => Test_utils.throws("File \"js_int_test.res\", line 75, characters 11-18", () => {
    (0).toString(1);
  }));
  Mocha.test("toStringWithRadix - radix:-1 throws", () => Test_utils.throws("File \"js_int_test.res\", line 79, characters 11-18", () => {
    (0).toString(-1);
  }));
});

/*  Not a pure module */
