// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Js_null_undefined from "@rescript/runtime/lib/es6/Js_null_undefined.js";

Mocha.describe("Js_null_undefined_test", () => {
  Mocha.test("toOption - null", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 7, characters 7-14", undefined, undefined));
  Mocha.test("toOption - undefined", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 10, characters 7-14", undefined, undefined));
  Mocha.test("toOption - empty", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 13, characters 7-14", undefined, undefined));
  Mocha.test("toOption - return", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 16, characters 7-14", "foo", Primitive_option.fromNullable("foo")));
  Mocha.test("return", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 19, characters 7-14", "something", Primitive_option.fromNullable("something")));
  Mocha.test("test - null", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 22, characters 7-14", true, true));
  Mocha.test("test - undefined", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 25, characters 7-14", true, true));
  Mocha.test("test - empty", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 28, characters 7-14", true, true));
  Mocha.test("test - return", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 31, characters 7-14", true, true));
  Mocha.test("bind - null", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 34, characters 7-14", null, Js_null_undefined.bind(null, v => v)));
  Mocha.test("bind - undefined", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 37, characters 7-14", undefined, Js_null_undefined.bind(undefined, v => v)));
  Mocha.test("bind - empty", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 40, characters 7-14", undefined, Js_null_undefined.bind(undefined, v => v)));
  Mocha.test("bind - 'a", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 43, characters 7-14", 4, Js_null_undefined.bind(2, n => (n << 1))));
  Mocha.test("iter - null", () => {
    let hit = {
      contents: false
    };
    Js_null_undefined.iter(null, param => {
      hit.contents = true;
    });
    Test_utils.eq("File \"js_null_undefined_test.res\", line 48, characters 7-14", false, hit.contents);
  });
  Mocha.test("iter - undefined", () => {
    let hit = {
      contents: false
    };
    Js_null_undefined.iter(undefined, param => {
      hit.contents = true;
    });
    Test_utils.eq("File \"js_null_undefined_test.res\", line 53, characters 7-14", false, hit.contents);
  });
  Mocha.test("iter - empty", () => {
    let hit = {
      contents: false
    };
    Js_null_undefined.iter(undefined, param => {
      hit.contents = true;
    });
    Test_utils.eq("File \"js_null_undefined_test.res\", line 58, characters 7-14", false, hit.contents);
  });
  Mocha.test("iter - 'a", () => {
    let hit = {
      contents: 0
    };
    Js_null_undefined.iter(2, v => {
      hit.contents = v;
    });
    Test_utils.eq("File \"js_null_undefined_test.res\", line 63, characters 7-14", 2, hit.contents);
  });
  Mocha.test("fromOption - None", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 66, characters 7-14", undefined, Js_null_undefined.fromOption(undefined)));
  Mocha.test("fromOption - Some", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 69, characters 7-14", 2, Js_null_undefined.fromOption(2)));
  Mocha.test("null <> undefined", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 72, characters 7-14", true, true));
  Mocha.test("null <> empty", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 75, characters 7-14", true, true));
  Mocha.test("undefined = empty", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 78, characters 7-14", true, true));
  Mocha.test("null variable", () => Test_utils.eq("File \"js_null_undefined_test.res\", line 82, characters 7-14", true, true));
});

/*  Not a pure module */
