// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function test_return_nullable(dom) {
  let elem = dom.getElementById("haha");
  if (elem == null) {
    return 1;
  } else {
    console.log(elem);
    return 2;
  }
}

function f(x, y) {
  console.log("no inline");
  return x + y | 0;
}

Mocha.describe("Js_nullable_test", () => {
  Mocha.test("Js.Nullable operations", () => {
    Test_utils.eq("File \"js_nullable_test.res\", line 25, characters 7-14", false, false);
    Test_utils.eq("File \"js_nullable_test.res\", line 26, characters 7-14", (f(1, 2) == null), false);
    Test_utils.eq("File \"js_nullable_test.res\", line 27, characters 7-14", (null == null), true);
    Test_utils.eq("File \"js_nullable_test.res\", line 31, characters 7-14", false, false);
  });
});

export {
  test_return_nullable,
  f,
}
/*  Not a pure module */
