// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Js_obj_test", () => {
  Mocha.test("empty", () => Test_utils.eq("File \"js_obj_test.res\", line 9, characters 7-14", 0, Object.keys({}).length));
  Mocha.test("assign", () => Test_utils.eq("File \"js_obj_test.res\", line 13, characters 7-14", {
    a: 1
  }, Object.assign({}, {
    a: 1
  })));
});

/*  Not a pure module */
