// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Js_undefined from "@rescript/runtime/lib/es6/Js_undefined.js";

Mocha.describe("Js_undefined_test", () => {
  Mocha.test("toOption - empty", () => Test_utils.eq("File \"js_undefined_test.res\", line 7, characters 7-14", undefined, Js_undefined.toOption(undefined)));
  Mocha.test("toOption - return", () => Test_utils.eq("File \"js_undefined_test.res\", line 10, characters 7-14", undefined, Js_undefined.toOption()));
  Mocha.test("return", () => Test_utils.eq("File \"js_undefined_test.res\", line 13, characters 7-14", "something", Js_undefined.toOption("something")));
  Mocha.test("test - empty", () => Test_utils.eq("File \"js_undefined_test.res\", line 16, characters 7-14", true, true));
  Mocha.test("test - return", () => Test_utils.eq("File \"js_undefined_test.res\", line 19, characters 7-14", true, true));
  Mocha.test("bind - empty", () => Test_utils.eq("File \"js_undefined_test.res\", line 22, characters 7-14", undefined, Js_undefined.bind(undefined, v => v)));
  Mocha.test("bind - 'a", () => Test_utils.eq("File \"js_undefined_test.res\", line 25, characters 7-14", 4, Js_undefined.bind(2, n => (n << 1))));
  Mocha.test("iter - empty", () => {
    let hit = {
      contents: false
    };
    Js_undefined.iter(undefined, param => {
      hit.contents = true;
    });
    Test_utils.eq("File \"js_undefined_test.res\", line 30, characters 7-14", false, hit.contents);
  });
  Mocha.test("iter - 'a", () => {
    let hit = {
      contents: 0
    };
    Js_undefined.iter(2, v => {
      hit.contents = v;
    });
    Test_utils.eq("File \"js_undefined_test.res\", line 35, characters 7-14", 2, hit.contents);
  });
  Mocha.test("fromOption - None", () => Test_utils.eq("File \"js_undefined_test.res\", line 38, characters 7-14", undefined, Js_undefined.fromOption(undefined)));
  Mocha.test("fromOption - Some", () => Test_utils.eq("File \"js_undefined_test.res\", line 41, characters 7-14", 2, Js_undefined.fromOption(2)));
});

/*  Not a pure module */
