// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

function u() {
  let n;
  try {
    n = "123".length;
  } catch (exn) {
    return 42;
  }
  return Primitive_int.div(3, 0);
}

Mocha.describe("Jsoo_400_test", () => {
  Mocha.test("jsoo_400 exception handling test", () => Test_utils.throws("File \"jsoo_400_test.res\", line 12, characters 11-18", () => {
    u();
  }));
});

export {
  u,
}
/*  Not a pure module */
