// Generated by ReScript, PLEASE EDIT WITH CARE


function handleKey(state, key) {
  if (key === "space" && state.active) {
    doAction(state);
    return;
  }
}

export {
  handleKey,
}
/* No side effect */
