// Generated by ReScript, PLEASE EDIT WITH CARE


function doStuffWithResult(s) {
  if (s === "s") {
    return {
      TAG: "Ok",
      _0: "hello"
    };
  } else {
    return {
      TAG: "Error",
      _0: "InvalidString"
    };
  }
}

function doNextStuffWithResult(s) {
  if (s === "s") {
    return {
      TAG: "Ok",
      _0: "hello"
    };
  } else {
    return {
      TAG: "Error",
      _0: "InvalidNext"
    };
  }
}

function getXWithResult(s) {
  let y = doStuffWithResult(s);
  if (y.TAG !== "Ok") {
    return y;
  }
  let y$1 = y._0;
  let x = doNextStuffWithResult(y$1);
  if (x.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: x._0 + y$1
    };
  } else {
    return x;
  }
}

let x = getXWithResult("s");

let someResult;

someResult = x.TAG === "Ok" ? x._0 : (
    x._0 === "InvalidNext" ? "nope!" : "nope"
  );

function doStuffWithOption(s) {
  if (s === "s") {
    return "hello";
  }
}

function doNextStuffWithOption(s) {
  if (s === "s") {
    return "hello";
  }
}

function getXWithOption(s) {
  let y = doStuffWithOption(s);
  if (y === undefined) {
    return y;
  }
  let x = doNextStuffWithOption(y);
  if (x !== undefined) {
    return x + y;
  } else {
    return x;
  }
}

let x$1 = getXWithOption("s");

let someOption = x$1 !== undefined ? x$1 : "nope";

async function doStuffResultAsync(s) {
  if (s === "s") {
    return {
      TAG: "Ok",
      _0: {
        s: "hello"
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: "FetchError"
    };
  }
}

async function decodeResAsync(res) {
  let match = res.s;
  if (match === "s") {
    return {
      TAG: "Ok",
      _0: res.s
    };
  } else {
    return {
      TAG: "Error",
      _0: "DecodeError"
    };
  }
}

async function getXWithResultAsync(s) {
  let x = await doStuffResultAsync(s);
  if (x.TAG !== "Ok") {
    return x;
  }
  let res = x._0;
  console.log(res.s);
  let x$1 = await decodeResAsync(res);
  if (x$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: x$1._0
    };
  } else {
    return x$1;
  }
}

function returnsAliasOnFirstError(s) {
  let _y = doStuffWithResult(s);
  if (_y.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: "ok"
    };
  } else {
    return _y;
  }
}

function returnsAliasOnSecondError(s) {
  let y = doStuffWithResult(s);
  if (y.TAG !== "Ok") {
    return y;
  }
  let _x = doNextStuffWithResult(y._0);
  if (_x.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: "ok"
    };
  } else {
    return _x;
  }
}

function returnsAliasOnOk(s) {
  let _e = doStuffWithResult(s);
  if (_e.TAG === "Ok") {
    return _e;
  } else {
    return {
      TAG: "Error",
      _0: "GotError"
    };
  }
}

export {
  doStuffWithResult,
  doNextStuffWithResult,
  getXWithResult,
  someResult,
  doStuffWithOption,
  doNextStuffWithOption,
  getXWithOption,
  someOption,
  doStuffResultAsync,
  decodeResAsync,
  getXWithResultAsync,
  returnsAliasOnFirstError,
  returnsAliasOnSecondError,
  returnsAliasOnOk,
}
/* x Not a pure module */
