// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

console.log(JSON.stringify({
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
}));

console.log("hey");

Mocha.describe("Lib_js_test", () => {
  Mocha.test("anything_to_string", () => Test_utils.eq("File \"lib_js_test.res\", line 13, characters 38-45", "3", String(3)));
});

/*  Not a pure module */
