// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_List from "@rescript/runtime/lib/es6/Belt_List.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let intEq = Primitive_object.equal;

Mocha.describe("List_test", () => {
  Mocha.test("length", () => Test_utils.eq("File \"list_test.res\", line 9, characters 7-14", 1, Belt_List.length({
    hd: [
      0,
      1,
      2,
      3,
      4
    ],
    tl: /* [] */0
  })));
  Mocha.test("length2", () => Test_utils.eq("File \"list_test.res\", line 13, characters 7-14", 5, Belt_List.length({
    hd: 0,
    tl: {
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 3,
          tl: {
            hd: 4,
            tl: /* [] */0
          }
        }
      }
    }
  })));
  Mocha.test("long_length", () => Test_utils.eq("File \"list_test.res\", line 18, characters 7-14", 30000, Belt_List.length(Belt_List.fromArray(Belt_Array.init(30000, param => 0)))));
  Mocha.test("sort", () => Test_utils.eq("File \"list_test.res\", line 23, characters 6-13", Belt_List.sort({
    hd: 4,
    tl: {
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 3,
          tl: /* [] */0
        }
      }
    }
  }, Primitive_int.compare), {
    hd: 1,
    tl: {
      hd: 2,
      tl: {
        hd: 3,
        tl: {
          hd: 4,
          tl: /* [] */0
        }
      }
    }
  }));
  Mocha.test("has true", () => Test_utils.eq("File \"list_test.res\", line 30, characters 7-14", true, Belt_List.has({
    hd: 1,
    tl: {
      hd: 2,
      tl: {
        hd: 3,
        tl: /* [] */0
      }
    }
  }, 3, intEq)));
  Mocha.test("has false", () => Test_utils.eq("File \"list_test.res\", line 34, characters 7-14", false, Belt_List.has({
    hd: 1,
    tl: {
      hd: 2,
      tl: {
        hd: 3,
        tl: /* [] */0
      }
    }
  }, 4, intEq)));
  Mocha.test("getAssoc", () => Test_utils.eq("File \"list_test.res\", line 38, characters 7-14", 9, Belt_List.getAssoc({
    hd: [
      1,
      2
    ],
    tl: {
      hd: [
        4,
        9
      ],
      tl: /* [] */0
    }
  }, 4, intEq)));
});

export {
  intEq,
}
/*  Not a pure module */
