// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f() {
  let v = {
    contents: 0
  };
  let acc = {
    contents: 0
  };
  let n = 10;
  while (true) {
    if (v.contents > n) {
      return acc.contents;
    }
    acc.contents = acc.contents + v.contents | 0;
    v.contents = v.contents + 1 | 0;
    continue;
  };
}

Mocha.describe("Loop_regression_test", () => {
  Mocha.test("sum", () => Test_utils.eq("File \"loop_regression_test.res\", line 21, characters 7-14", 55, f()));
});

export {
  f,
}
/*  Not a pure module */
