// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_List from "@rescript/runtime/lib/es6/Belt_List.js";
import * as Test_utils from "./test_utils.mjs";
import * as Belt_MapInt from "@rescript/runtime/lib/es6/Belt_MapInt.js";
import * as Belt_MapString from "@rescript/runtime/lib/es6/Belt_MapString.js";

let m = Belt_List.reduceReverse({
  hd: [
    10,
    /* 'a' */97
  ],
  tl: {
    hd: [
      3,
      /* 'b' */98
    ],
    tl: {
      hd: [
        7,
        /* 'c' */99
      ],
      tl: {
        hd: [
          20,
          /* 'd' */100
        ],
        tl: /* [] */0
      }
    }
  }
}, undefined, (acc, param) => Belt_MapInt.set(acc, param[0], param[1]));

let s = Belt_List.reduceReverse({
  hd: [
    "10",
    /* 'a' */97
  ],
  tl: {
    hd: [
      "3",
      /* 'b' */98
    ],
    tl: {
      hd: [
        "7",
        /* 'c' */99
      ],
      tl: {
        hd: [
          "20",
          /* 'd' */100
        ],
        tl: /* [] */0
      }
    }
  }
}, undefined, (acc, param) => Belt_MapString.set(acc, param[0], param[1]));

Mocha.describe("Map_find_test", () => {
  Mocha.test("int", () => Test_utils.eq("File \"map_find_test.res\", line 24, characters 7-14", Belt_MapInt.get(m, 10), /* 'a' */97));
  Mocha.test("string", () => Test_utils.eq("File \"map_find_test.res\", line 28, characters 7-14", Belt_MapString.get(s, "10"), /* 'a' */97));
});

let IntMap;

let empty;

let SMap;

export {
  IntMap,
  empty,
  m,
  SMap,
  s,
}
/* m Not a pure module */
