// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(x, i, file, v) {
  x.case(i);
  x.case__set(i, v);
  x._open(file);
  x.open__(file);
  return x._MAX_LENGTH;
}

function ff(x, i, v) {
  x.make__config = v;
  x.make_config = v;
  x.case__unsafe(i);
  return x._open__(3);
}

let u = {
  "_Content'type": "x"
};

let h = {
  _open: 3,
  _end: 32
};

function hg(x) {
  return x._open + x._end | 0;
}

Mocha.describe("Method_name_test", () => {
  Mocha.test("method name test", () => Test_utils.eq("File \"method_name_test.res\", line 36, characters 7-14", 35, hg(h)));
});

export {
  f,
  ff,
  u,
  h,
  hg,
}
/*  Not a pure module */
