// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Stdlib_String from "@rescript/runtime/lib/es6/Stdlib_String.js";

function u(v) {
  return v;
}

let s = Stdlib_String;

let N = {
  s: s
};

let v0 = "x".length;

function v(x) {
  return x.length;
}

Mocha.describe("Module_parameter_test", () => {
  Mocha.test("const", () => Test_utils.eq("File \"module_parameter_test.res\", line 24, characters 7-14", 1, v0));
  Mocha.test("other", () => Test_utils.eq("File \"module_parameter_test.res\", line 28, characters 7-14", 3, v("abc")));
});

export {
  u,
  N,
  v0,
  v,
}
/* v0 Not a pure module */
