// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import JoinClassesMjs from "./joinClasses.mjs";

function joinClasses(prim) {
  return JoinClassesMjs(...prim);
}

let a = JoinClassesMjs(1, 2, 3);

let pair = [
  a,
  6
];

console.log(pair);

Mocha.describe("Module_splice_test", () => {
  Mocha.test("joinClasses module splice", () => Test_utils.eq("File \"module_splice_test.res\", line 14, characters 45-52", a, 6));
});

export {
  joinClasses,
  a,
}
/* a Not a pure module */
