// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_List from "@rescript/runtime/lib/es6/Belt_List.js";
import * as Test_utils from "./test_utils.mjs";

function f(x) {
  console.log(x);
  console.log(Belt_List.length(x));
  return Belt_List;
}

let h = f(/* [] */0);

let a = h.length({
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
});

Test_utils.eq("File \"module_alias_test.res\", line 26, characters 3-10", a, 3);

Mocha.describe("Module_alias_test", () => {
  Mocha.test("module_alias_test", () => Test_utils.eq("File \"module_alias_test.res\", line 29, characters 7-14", a, 3));
});

let N;

let V;

let J;

export {
  N,
  V,
  J,
  f,
  a,
}
/* h Not a pure module */
