// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Stdlib_Lazy from "@rescript/runtime/lib/es6/Stdlib_Lazy.js";

function f(x) {
  return Stdlib_Lazy.get(x) + "abc";
}

Mocha.describe("Mpr_6033_test", () => {
  Mocha.test("lazy evaluation", () => {
    let x = Stdlib_Lazy.from_fun(() => "def");
    Stdlib_Lazy.get(x);
    let u = Stdlib_Lazy.get(x) + "abc";
    Test_utils.eq("File \"mpr_6033_test.res\", line 14, characters 7-14", u, "defabc");
  });
});

export {
  f,
}
/*  Not a pure module */
