// Generated by ReScript, PLEASE EDIT WITH CARE


function foo() {
  return ["foo"];
}

let bar = ["foo"];

function nested() {
  return 1;
}

let baz = 1;

export {
  foo,
  bar,
  nested,
  baz,
}
/* No side effect */
