// Generated by ReScript, PLEASE EDIT WITH CARE


let a = {
  TAG: "One",
  _0: {
    one: "1",
    two: 2
  }
};

let b = {
  TAG: "Two",
  one: "1",
  two: 2
};

export {
  a,
  b,
}
/* No side effect */
