// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(s, b, i, param) {
  let tmp = {};
  if (s !== undefined) {
    tmp.s = Primitive_option.valFromOption(s);
  }
  if (b !== undefined) {
    tmp.b = Primitive_option.valFromOption(b);
  }
  if (i !== undefined) {
    tmp.i = Primitive_option.valFromOption(i);
  }
  return tmp;
}

let hh = {
  s: "",
  b: false,
  i: 0
};

Mocha.describe("Optional_regression_test", () => {
  Mocha.test("optional regression test", () => {
    Test_utils.eq("File \"optional_regression_test.res\", line 17, characters 7-14", hh.s, "");
    Test_utils.eq("File \"optional_regression_test.res\", line 18, characters 7-14", hh.b, false);
    Test_utils.eq("File \"optional_regression_test.res\", line 19, characters 7-14", hh.i, 0);
  });
});

export {
  make,
  hh,
}
/*  Not a pure module */
