// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let f = ((a) => typeof a);

let a = f(3);

let b = f("3");

Mocha.describe("Polymorphic_raw_test", () => {
  Mocha.test("polymorphic raw test", () => {
    Test_utils.eq("File \"polymorphic_raw_test.res\", line 15, characters 7-14", a, "number");
    Test_utils.eq("File \"polymorphic_raw_test.res\", line 16, characters 7-14", b, "string");
  });
});

export {
  f,
  a,
  b,
}
/* a Not a pure module */
