// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(h, param) {
  console.log(3);
  return (x, y) => h(x, y);
}

Mocha.describe("Print_alpha_test", () => {
  Mocha.test("File \"print_alpha_test.res\", line 16, characters 7-14", () => Test_utils.eq("File \"print_alpha_test.res\", line 17, characters 7-14", 3, f((prim0, prim1) => prim0 + prim1 | 0, undefined)(1, 2)));
});

export {
  f,
}
/*  Not a pure module */
