// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let v = {
  a: 3,
  b: {
    xx: 2,
    yy: 3
  }
};

let u_a = 2;

let u_b = v.b;

let u = {
  a: u_a,
  b: u_b
};

let A = /* @__PURE__ */Primitive_exceptions.create("Record_debug_test.A");

let B = /* @__PURE__ */Primitive_exceptions.create("Record_debug_test.B");

let v0 = {
  RE_EXN_ID: A,
  _1: 3
};

let v1 = {
  RE_EXN_ID: B,
  _1: 3,
  _2: 2
};

let N = {
  a: 0,
  b: 1
};

function N0_f(prim) {
  return prim;
}

let N0 = {
  a: 0,
  b: 1,
  f: N0_f
};

console.log("hei", v);

let a = [
  1,
  2,
  2,
  4,
  3
];

let c = [
  1,
  2,
  3,
  4,
  5
];

console.log(a, c);

Mocha.describe("record_debug_test.res", () => {
  Mocha.test("private attribute test", () => Test_utils.eq("File \"record_debug_test.res\", line 57, characters 7-14", [
    ``,
    `a`
  ], [
    "",
    "a"
  ]));
});

let h = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: {
        hd: 4,
        tl: /* [] */0
      }
    }
  }
};

let v2 = {
  NAME: "C",
  VAL: 2
};

let v3 = {
  NAME: "C",
  VAL: [
    2,
    3
  ]
};

export {
  v,
  u,
  h,
  A,
  B,
  v0,
  v1,
  v2,
  v3,
  N,
  N0,
  a,
  c,
}
/*  Not a pure module */
