// Generated by ReScript, PLEASE EDIT WITH CARE


function getY(v) {
  return v.y;
}

function getX(v) {
  return v.x;
}

let DeepSub = {
  d: {
    x: {
      TAG: "Ok",
      _0: 1
    },
    z: {
      NAME: "Two",
      VAL: 1
    }
  }
};

let v = {
  y: 3,
  x: 3
};

let d = {
  a: "",
  b: 1,
  c: undefined,
  d: {
    TAG: "Ok",
    _0: 1
  }
};

let x = {
  c: "hello"
};

let v1 = {
  TAG: "One",
  a: "",
  b: 1,
  c: undefined,
  d: undefined
};

let v2 = {
  TAG: "Two",
  a: "",
  b: "1",
  c: undefined,
  d: undefined
};

let v3 = {
  TAG: "Three",
  a: "",
  b: true,
  c: undefined,
  d: undefined
};

export {
  getY,
  getX,
  v,
  d,
  x,
  DeepSub,
  v1,
  v2,
  v3,
}
/* No side effect */
