// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let v = {
  syntax: undefined,
  imports: 0,
  file_options: 0,
  package: 0,
  messages: 0,
  enums: 0,
  extends: 0
};

let u_v = {
  syntax: undefined,
  imports: 0,
  file_options: 0,
  package: 0,
  messages: 0,
  enums: 0,
  extends: 0
};

function f(g, h) {
  let init = g(h);
  return {
    syntax: init.syntax,
    imports: 0,
    file_options: init.file_options,
    package: init.package,
    messages: init.messages,
    enums: init.enums,
    extends: init.extends
  };
}

Mocha.describe("Record_with_test", () => {
  Mocha.test("eq_with", () => Test_utils.eq("File \"record_with_test.res\", line 39, characters 7-14", v, u_v));
});

let uv = {
  syntax: undefined,
  imports: 1,
  file_options: 0,
  package: 0,
  messages: 0,
  enums: 0,
  extends: 0
};

export {
  v,
  uv,
  u_v,
  f,
}
/*  Not a pure module */
