// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_List from "@rescript/runtime/lib/es6/Belt_List.js";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let rec_cell = {};

rec_cell.content = 3;

rec_cell.next = rec_cell;

function f0(x) {
  let rec_cell = {};
  Primitive_object.updateDummy(rec_cell, {
    content: (x * x | 0) - 6 | 0,
    next: rec_cell
  });
  return rec_cell;
}

function a0(x) {
  return (x.content + x.next.content | 0) + x.next.next.content | 0;
}

let rec_cell2 = {};

rec_cell2.content = 3;

rec_cell2.next = rec_cell2;

function f2(x) {
  let rec_cell2 = {};
  Primitive_object.updateDummy(rec_cell2, {
    TAG: "Cons",
    content: (x * x | 0) - 6 | 0,
    next: rec_cell2
  });
  return rec_cell2;
}

function hd(x) {
  if (typeof x !== "object") {
    return 0;
  } else {
    return x.content;
  }
}

function tl_exn(x) {
  if (typeof x === "object") {
    return x.next;
  }
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "recursive_records_test.res",
      43,
      11
    ],
    Error: new Error()
  };
}

let rec_cell3 = {};

rec_cell3.hd = 3;

rec_cell3.tl = rec_cell3;

function f3(x) {
  let rec_cell3 = {};
  Primitive_object.updateDummy(rec_cell3, {
    hd: (x * x | 0) - 6 | 0,
    tl: rec_cell3
  });
  return rec_cell3;
}

Mocha.describe("Recursive_records_test", () => {
  Mocha.test("recursive record operations", () => {
    Test_utils.eq("File \"recursive_records_test.res\", line 56, characters 7-14", a0(rec_cell), 9);
    Test_utils.eq("File \"recursive_records_test.res\", line 57, characters 7-14", a0(f0(3)), 9);
  });
  Mocha.test("recursive inline record operations", () => {
    Test_utils.eq("File \"recursive_records_test.res\", line 61, characters 7-14", (hd(rec_cell2) + hd(tl_exn(rec_cell2)) | 0) + hd(tl_exn(tl_exn(rec_cell2))) | 0, 9);
    let rec_cell2$1 = f2(3);
    Test_utils.eq("File \"recursive_records_test.res\", line 63, characters 7-14", (hd(rec_cell2$1) + hd(tl_exn(rec_cell2$1)) | 0) + hd(tl_exn(tl_exn(rec_cell2$1))) | 0, 9);
  });
  Mocha.test("recursive variant list operations", () => {
    Test_utils.eq("File \"recursive_records_test.res\", line 69, characters 7-14", (Belt_List.headExn(rec_cell3) + Belt_List.headExn(Belt_List.tailExn(rec_cell3)) | 0) + Belt_List.headExn(Belt_List.tailExn(Belt_List.tailExn(rec_cell3))) | 0, 9);
    let rec_cell3$1 = f3(3);
    Test_utils.eq("File \"recursive_records_test.res\", line 71, characters 7-14", (Belt_List.headExn(rec_cell3$1) + Belt_List.headExn(Belt_List.tailExn(rec_cell3$1)) | 0) + Belt_List.headExn(Belt_List.tailExn(Belt_List.tailExn(rec_cell3$1))) | 0, 9);
  });
});

export {
  rec_cell,
  f0,
  a0,
  rec_cell2,
  f2,
  hd,
  tl_exn,
  rec_cell3,
  f3,
}
/*  Not a pure module */
