// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_module from "@rescript/runtime/lib/es6/Primitive_module.js";

let Int3 = Primitive_module.init([
  "recursive_module_test.res",
  6,
  4
], {
  TAG: "Module",
  _0: [[
      "Function",
      "u"
    ]]
});

Primitive_module.update({
  TAG: "Module",
  _0: [[
      "Function",
      "u"
    ]]
}, Int3, Int3);

let M = Primitive_module.init([
  "recursive_module_test.res",
  12,
  20
], {
  TAG: "Module",
  _0: [[
      "Function",
      "fact"
    ]]
});

function fact(n) {
  if (n <= 1) {
    return 1;
  } else {
    return n * M.fact(n - 1 | 0) | 0;
  }
}

Primitive_module.update({
  TAG: "Module",
  _0: [[
      "Function",
      "fact"
    ]]
}, M, {
  fact: fact
});

let fact$1 = M.fact;

let Fact = {
  M: M,
  fact: fact$1
};

Mocha.describe("Recursive_module_test", () => {
  Mocha.test("recursive module factorial", () => Test_utils.eq("File \"recursive_module_test.res\", line 25, characters 7-14", 120, fact$1(5)));
  Mocha.test("recursive module exception", () => Test_utils.throws("File \"recursive_module_test.res\", line 29, characters 11-18", () => {
    Int3.u(3);
  }));
});

export {
  Int3,
  Fact,
}
/* Int3 Not a pure module */
