// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

console.log("你好");

console.log(`你好`);

console.log("你好");

function f(x) {
  if (x !== 333) {
    if (x >= 256) {
      return 3;
    } else {
      return 0;
    }
  } else {
    return 2;
  }
}

Mocha.describe("String_unicode_test", () => {
  Mocha.test("switch", () => {
    Test_utils.eq("File \"string_unicode_test.res\", line 19, characters 7-14", f(/* '{' */123), 0);
    Test_utils.eq("File \"string_unicode_test.res\", line 20, characters 7-14", f(/* 'ō' */333), 2);
    Test_utils.eq("File \"string_unicode_test.res\", line 21, characters 7-14", f(/* 'Ƽ' */444), 3);
  });
});

export {
  f,
}
/*  Not a pure module */
