// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as String_set from "./string_set.mjs";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("String_set_test", () => {
  Mocha.test("String_set cardinality", () => {
    let s = String_set.empty;
    for (let i = 0; i <= 99999; ++i) {
      s = String_set.add(i.toString(), s);
    }
    Test_utils.eq("File \"string_set_test.res\", line 11, characters 7-14", String_set.cardinal(s), 100000);
  });
});

/*  Not a pure module */
