// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(x) {
  switch (x) {
    case "xx'''" :
      return 0;
    case "xx\"" :
      return 1;
    case "xx\\\"" :
      return 2;
    case "xx\\\"\"" :
      return 3;
    default:
      return 4;
  }
}

Mocha.describe("Switch_case_test", () => {
  Mocha.test("switch case with escaped strings", () => {
    Test_utils.eq("File \"switch_case_test.res\", line 15, characters 7-14", f("xx'''"), 0);
    Test_utils.eq("File \"switch_case_test.res\", line 16, characters 7-14", f("xx\""), 1);
    Test_utils.eq("File \"switch_case_test.res\", line 17, characters 7-14", f(`xx\\"`), 2);
    Test_utils.eq("File \"switch_case_test.res\", line 18, characters 7-14", f(`xx\\""`), 3);
  });
});

export {
  f,
}
/*  Not a pure module */
