// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Test_utils from "./test_utils.mjs";

function f() {
  let f$1 = (_acc, _n) => {
    while (true) {
      let n = _n;
      let acc = _acc;
      if (n <= 0) {
        return acc;
      }
      _n = n - 1 | 0;
      _acc = acc + n | 0;
      continue;
    };
  };
  let v = Belt_Array.make(10, 0);
  for (let i = 0; i <= 9; ++i) {
    v[i] = f$1(0, i);
  }
  return v;
}

Mocha.describe("Tailcall_inline_test", () => {
  Mocha.test("acc", () => Test_utils.eq("File \"tailcall_inline_test.res\", line 21, characters 7-14", [
    0,
    1,
    3,
    6,
    10,
    15,
    21,
    28,
    36,
    45
  ], f()));
});

export {
  f,
}
/*  Not a pure module */
