// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

Mocha.describe("Test_string_const", () => {
  Mocha.test("getUnsafe", () => {
    Test_utils.eq("File \"test_string_const.res\", line 6, characters 7-14", "ghsogh".codePointAt(3), 111);
    Test_utils.eq("File \"test_string_const.res\", line 7, characters 7-14", "ghsogh".codePointAt(-3), undefined);
  });
});

/*  Not a pure module */
