// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodeassert from "node:assert";

function ok(loc, a) {
  Nodeassert.ok(a, loc);
}

function eq(loc, a, b) {
  Nodeassert.deepStrictEqual(a, b, loc);
}

function throws(loc, f) {
  Nodeassert.throws(f, undefined, loc);
}

function approxEq(loc, threshold, a, b) {
  let diff = Math.abs(a - b);
  Nodeassert.ok(diff <= threshold, loc);
}

export {
  ok,
  eq,
  throws,
  approxEq,
}
/* node:assert Not a pure module */
