// Generated by ReScript, PLEASE EDIT WITH CARE


let node_modules_length = "node_modules".length;

let node_modules = "node_modules";

export {
  node_modules,
  node_modules_length,
}
/* node_modules_length Not a pure module */
