// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(xOpt, y) {
  let x = xOpt !== undefined ? xOpt : 3;
  let xOpt$1 = x + 2 | 0;
  console.log(xOpt$1);
  return xOpt$1 + y | 0;
}

Mocha.describe("Test_case_opt_collision", () => {
  Mocha.test("optional parameter collision", () => {
    console.log(f(undefined, 2));
    Test_utils.eq("File \"test_case_opt_collision.res\", line 13, characters 7-14", f(undefined, 2), 7);
    Test_utils.eq("File \"test_case_opt_collision.res\", line 14, characters 7-14", f(4, 2), 8);
  });
});

export {
  f,
}
/*  Not a pure module */
