// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function then(a, b) {
  console.log("no inline");
  return (a * a | 0) + (b * b | 0) | 0;
}

Mocha.describe("Then_mangle_test", () => {
  Mocha.test("then function mangling", () => Test_utils.eq("File \"then_mangle_test.res\", line 13, characters 7-14", then(1, 2), 5));
});

/*  Not a pure module */
