// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function fib(n, k) {
  if (n !== 0 && n !== 1) {
    return {
      TAG: "Suspend",
      _0: () => fib(n - 1 | 0, v0 => fib(n - 2 | 0, v1 => k(v0 + v1 | 0)))
    };
  } else {
    return k(1);
  }
}

let u = fib(10, x => ({
  TAG: "Continue",
  _0: x
}));

function iter(_bounce) {
  while (true) {
    let bounce = _bounce;
    if (bounce.TAG === "Continue") {
      return bounce._0;
    }
    _bounce = bounce._0();
    continue;
  };
}

function isEven(n) {
  if (n !== 0) {
    if (n !== 1) {
      return {
        TAG: "Suspend",
        _0: () => isOdd(n - 1 | 0)
      };
    } else {
      return {
        TAG: "Continue",
        _0: false
      };
    }
  } else {
    return {
      TAG: "Continue",
      _0: true
    };
  }
}

function isOdd(n) {
  if (n !== 0) {
    if (n !== 1) {
      return isEven(n - 1 | 0);
    } else {
      return {
        TAG: "Continue",
        _0: true
      };
    }
  } else {
    return {
      TAG: "Continue",
      _0: false
    };
  }
}

Mocha.describe("Tramp_fib", () => {
  Mocha.test("fibonacci trampoline", () => Test_utils.eq("File \"tramp_fib.res\", line 55, characters 7-14", iter(u), 89));
  Mocha.test("even/odd trampoline", () => Test_utils.eq("File \"tramp_fib.res\", line 59, characters 7-14", iter(isEven(20000)), true));
});

export {
  fib,
  u,
  iter,
  isEven,
  isOdd,
}
/* u Not a pure module */
