// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Js_types from "@rescript/runtime/lib/es6/Js_types.js";
import * as Test_utils from "./test_utils.mjs";

function string_or_number(x) {
  let ty = Js_types.classify(x);
  if (typeof ty !== "object") {
    switch (ty) {
      default:
        return false;
    }
  } else {
    switch (ty.TAG) {
      case "JSNumber" :
        console.log(ty._0 + 3);
        return true;
      case "JSString" :
        console.log(ty._0 + "hei");
        return true;
      case "JSFunction" :
        console.log("Function");
        return false;
      case "JSBigInt" :
        console.log(ty._0.toString());
        return true;
      default:
        return false;
    }
  }
}

Mocha.describe("Typeof_test", () => {
  Mocha.test("int_type", () => Test_utils.eq("File \"typeof_test.res\", line 29, characters 7-14", "number", "number"));
  Mocha.test("string_type", () => Test_utils.eq("File \"typeof_test.res\", line 33, characters 7-14", "string", "string"));
  Mocha.test("number_gadt_test", () => Test_utils.eq("File \"typeof_test.res\", line 37, characters 7-14", Js_types.test(3, "Number"), true));
  Mocha.test("boolean_gadt_test", () => Test_utils.eq("File \"typeof_test.res\", line 41, characters 7-14", Js_types.test(true, "Boolean"), true));
  Mocha.test("undefined_gadt_test", () => Test_utils.eq("File \"typeof_test.res\", line 45, characters 7-14", Js_types.test(undefined, "Undefined"), true));
  Mocha.test("string_on_number1", () => Test_utils.eq("File \"typeof_test.res\", line 49, characters 7-14", string_or_number("xx"), true));
  Mocha.test("string_on_number2", () => Test_utils.eq("File \"typeof_test.res\", line 53, characters 7-14", string_or_number(3.02), true));
  Mocha.test("string_on_number3", () => Test_utils.eq("File \"typeof_test.res\", line 57, characters 7-14", string_or_number(x => x), false));
  Mocha.test("string_gadt_test", () => Test_utils.eq("File \"typeof_test.res\", line 61, characters 7-14", Js_types.test("3", "String"), true));
  Mocha.test("string_gadt_test_neg", () => Test_utils.eq("File \"typeof_test.res\", line 65, characters 7-14", Js_types.test(3, "String"), false));
  Mocha.test("function_gadt_test", () => Test_utils.eq("File \"typeof_test.res\", line 69, characters 7-14", Js_types.test(x => x, "Function"), true));
  Mocha.test("object_gadt_test", () => Test_utils.eq("File \"typeof_test.res\", line 73, characters 7-14", Js_types.test({
    x: 3
  }, "Object"), true));
});

export {
  string_or_number,
}
/*  Not a pure module */
