// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function make(x) {
  return x;
}

function get(x) {
  return x;
}

let x = "foo";

Test_utils.eq("File \"unboxed_attribute_test.res\", line 18, characters 4-11", x, x);

let x$1 = "foo";

Test_utils.eq("File \"unboxed_attribute_test.res\", line 33, characters 5-12", x$1, x$1);

let x$2 = "foo";

Test_utils.eq("File \"unboxed_attribute_test.res\", line 42, characters 4-11", x$2, x$2);

let y = {};

y._0 = y;

Mocha.describe("Unboxed_attribute_test", () => {
  Mocha.test("unboxed_attribute_tests", () => Test_utils.ok("File \"unboxed_attribute_test.res\", line 58, characters 7-14", true));
});

let v0 = 3;

export {
  v0,
  make,
  get,
  y,
}
/*  Not a pure module */
