// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function sum(a,b){
  return a + b
}
;

Mocha.describe("Uncurry_external_test", () => {
  Mocha.test("uncurried external function call", () => {
    let h = sum(1.0, 2.0);
    Test_utils.eq("File \"uncurry_external_test.res\", line 15, characters 7-14", h, 3);
  });
});

/*  Not a pure module */
