// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_undefined from "@rescript/runtime/lib/es6/Js_undefined.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";

function f(obj) {
  if (typeof obj === "function") {
    return;
  }
  let size = obj.length;
  let s = Js_undefined.toOption(size);
  if (s !== undefined) {
    console.log(Primitive_option.valFromOption(s));
    return;
  }
}

export {
  f,
}
/* No side effect */
