// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function f_01() {
  return hi(x => {
    if (x === undefined) {
      console.log("x");
      return;
    }
    
  });
}

function u(x) {
  if (x > 3) {
    return 1;
  } else if (x < 2) {
    return 2;
  } else if (x > 4) {
    return 0;
  } else {
    return 3;
  }
}

function fx() {
  
}

function u0(x) {
  return Primitive_option.some(x);
}

let u1 = Primitive_option.some(undefined);

function u2(x) {
  return Primitive_option.some(x);
}

let u3 = Primitive_option.some(undefined);

Mocha.describe("Unit_undefined_test", () => {
  Mocha.test("unit undefined test", () => {
    Test_utils.eq("File \"unit_undefined_test.res\", line 34, characters 7-14", Primitive_option.some(), Primitive_option.some(undefined));
    Test_utils.eq("File \"unit_undefined_test.res\", line 35, characters 7-14", u1, Primitive_option.some(undefined));
    Test_utils.eq("File \"unit_undefined_test.res\", line 36, characters 7-14", Primitive_option.some(), Primitive_option.some(undefined));
    Test_utils.eq("File \"unit_undefined_test.res\", line 37, characters 7-14", u3, Primitive_option.some(undefined));
    Test_utils.eq("File \"unit_undefined_test.res\", line 38, characters 7-14", undefined, undefined);
  });
});

let u4;

export {
  f_01,
  u,
  fx,
  u0,
  u1,
  u2,
  u3,
  u4,
}
/*  Not a pure module */
