// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as Test_utils from "./test_utils.mjs";
import * as Ffi_js_test from "./ffi_js_test.mjs";

let x = "\\x01\\x02\\x03";

let max = Math.max;

function $$test(x,y){
  return x + y;
}
;

let regression3 = Math.max;

let regression4 = Math.max;

function g(a) {
  let regression = (function(x,y){
   return ""
});
  let regression2 = Math.max;
  regression(a, Pervasives.failwith);
  regression2(3, 2);
  regression3(3, 2);
  regression4(3, x => x);
}

let max2 = Math.max;

function umax(a, b) {
  return max2(a, b);
}

function u(h) {
  return max2(3, h);
}

let max3 = Math.max;

function uu(h) {
  return max2(3, h);
}

let empty = Object.keys(3);

let v = $$test(1, 2);

Mocha.describe("Unsafe_ppx_test", () => {
  Mocha.test("unsafe_max", () => Test_utils.eq("File \"unsafe_ppx_test.res\", line 56, characters 7-14", 2, max(1, 2)));
  Mocha.test("unsafe_test", () => Test_utils.eq("File \"unsafe_ppx_test.res\", line 59, characters 7-14", 3, v));
  Mocha.test("unsafe_max2", () => Test_utils.eq("File \"unsafe_ppx_test.res\", line 62, characters 7-14", 2, Math.max(1, 2)));
  Mocha.test("ffi_keys", () => Test_utils.eq("File \"unsafe_ppx_test.res\", line 65, characters 7-14", ["a"], Ffi_js_test.keys({a : 3})));
});

export {
  x,
  max,
  regression3,
  regression4,
  g,
  max2,
  umax,
  u,
  max3,
  uu,
  empty,
  v,
}
/* max Not a pure module */
