// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function f(x) {
  let y = {...x};
  return {
    a0: 1,
    a1: y.a1,
    a2: y.a2,
    a3: y.a3,
    a4: y.a4,
    a5: y.a5
  };
}

Mocha.describe("Update_record_test", () => {
  Mocha.test("record update operations", () => Test_utils.eq("File \"update_record_test.res\", line 25, characters 7-14", 1, f({
    a0: 0,
    a1: 0,
    a2: 0,
    a3: 0,
    a4: 0,
    a5: 0
  }).a0));
  Mocha.test("record update with invalid js id", () => {
    let fff = x => ({
      "invalid_js_id'": x["invalid_js_id'"] + 2 | 0,
      x: x.x
    });
    let val1 = fff({
      "invalid_js_id'": 3,
      x: 2
    });
    Test_utils.eq("File \"update_record_test.res\", line 32, characters 7-14", 3, 3);
    Test_utils.eq("File \"update_record_test.res\", line 33, characters 7-14", val1["invalid_js_id'"], 5);
  });
});

export {
  f,
}
/*  Not a pure module */
